# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

abbr --add k "kubectl"
abbr --add ksys "kubectl --namespace=kube-system"
abbr --add ka "kubectl apply --recursive -f"
abbr --add ksysa "kubectl --namespace=kube-system apply --recursive -f"
abbr --add kak "kubectl apply -k"
abbr --add kk "kubectl kustomize"
abbr --add kex "kubectl exec -i -t"
abbr --add ksysex "kubectl --namespace=kube-system exec -i -t"
abbr --add klo "kubectl logs -f"
abbr --add ksyslo "kubectl --namespace=kube-system logs -f"
abbr --add klop "kubectl logs -f -p"
abbr --add ksyslop "kubectl --namespace=kube-system logs -f -p"
abbr --add kp "kubectl proxy"
abbr --add kpf "kubectl port-forward"
abbr --add kg "kubectl get"
abbr --add ksysg "kubectl --namespace=kube-system get"
abbr --add kd "kubectl describe"
abbr --add ksysd "kubectl --namespace=kube-system describe"
abbr --add krm "kubectl delete"
abbr --add ksysrm "kubectl --namespace=kube-system delete"
abbr --add krun "kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add ksysrun "kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add kgpo "kubectl get pods"
abbr --add ksysgpo "kubectl --namespace=kube-system get pods"
abbr --add kdpo "kubectl describe pods"
abbr --add ksysdpo "kubectl --namespace=kube-system describe pods"
abbr --add krmpo "kubectl delete pods"
abbr --add ksysrmpo "kubectl --namespace=kube-system delete pods"
abbr --add kgdep "kubectl get deployment"
abbr --add ksysgdep "kubectl --namespace=kube-system get deployment"
abbr --add kddep "kubectl describe deployment"
abbr --add ksysddep "kubectl --namespace=kube-system describe deployment"
abbr --add krmdep "kubectl delete deployment"
abbr --add ksysrmdep "kubectl --namespace=kube-system delete deployment"
abbr --add kgss "kubectl get statefulset"
abbr --add ksysgss "kubectl --namespace=kube-system get statefulset"
abbr --add kdss "kubectl describe statefulset"
abbr --add ksysdss "kubectl --namespace=kube-system describe statefulset"
abbr --add krmss "kubectl delete statefulset"
abbr --add ksysrmss "kubectl --namespace=kube-system delete statefulset"
abbr --add kgds "kubectl get daemonset"
abbr --add ksysgds "kubectl --namespace=kube-system get daemonset"
abbr --add kdds "kubectl describe daemonset"
abbr --add ksysdds "kubectl --namespace=kube-system describe daemonset"
abbr --add krmds "kubectl delete daemonset"
abbr --add ksysrmds "kubectl --namespace=kube-system delete daemonset"
abbr --add kgjob "kubectl get job"
abbr --add ksysgjob "kubectl --namespace=kube-system get job"
abbr --add kdjob "kubectl describe job"
abbr --add ksysdjob "kubectl --namespace=kube-system describe job"
abbr --add krmjob "kubectl delete job"
abbr --add ksysrmjob "kubectl --namespace=kube-system delete job"
abbr --add kgcjob "kubectl get cronjob"
abbr --add ksysgcjob "kubectl --namespace=kube-system get cronjob"
abbr --add kdcjob "kubectl describe cronjob"
abbr --add ksysdcjob "kubectl --namespace=kube-system describe cronjob"
abbr --add krmcjob "kubectl delete cronjob"
abbr --add ksysrmcjob "kubectl --namespace=kube-system delete cronjob"
abbr --add kgsvc "kubectl get service"
abbr --add ksysgsvc "kubectl --namespace=kube-system get service"
abbr --add kdsvc "kubectl describe service"
abbr --add ksysdsvc "kubectl --namespace=kube-system describe service"
abbr --add krmsvc "kubectl delete service"
abbr --add ksysrmsvc "kubectl --namespace=kube-system delete service"
abbr --add kging "kubectl get ingress"
abbr --add ksysging "kubectl --namespace=kube-system get ingress"
abbr --add kding "kubectl describe ingress"
abbr --add ksysding "kubectl --namespace=kube-system describe ingress"
abbr --add krming "kubectl delete ingress"
abbr --add ksysrming "kubectl --namespace=kube-system delete ingress"
abbr --add kgcm "kubectl get configmap"
abbr --add ksysgcm "kubectl --namespace=kube-system get configmap"
abbr --add kdcm "kubectl describe configmap"
abbr --add ksysdcm "kubectl --namespace=kube-system describe configmap"
abbr --add krmcm "kubectl delete configmap"
abbr --add ksysrmcm "kubectl --namespace=kube-system delete configmap"
abbr --add kgsec "kubectl get secret"
abbr --add ksysgsec "kubectl --namespace=kube-system get secret"
abbr --add kdsec "kubectl describe secret"
abbr --add ksysdsec "kubectl --namespace=kube-system describe secret"
abbr --add krmsec "kubectl delete secret"
abbr --add ksysrmsec "kubectl --namespace=kube-system delete secret"
abbr --add kgsc "kubectl get storageclass"
abbr --add ksysgsc "kubectl --namespace=kube-system get storageclass"
abbr --add kdsc "kubectl describe storageclass"
abbr --add ksysdsc "kubectl --namespace=kube-system describe storageclass"
abbr --add krmsc "kubectl delete storageclass"
abbr --add ksysrmsc "kubectl --namespace=kube-system delete storageclass"
abbr --add kgpv "kubectl get persistentvolume"
abbr --add ksysgpv "kubectl --namespace=kube-system get persistentvolume"
abbr --add kdpv "kubectl describe persistentvolume"
abbr --add ksysdpv "kubectl --namespace=kube-system describe persistentvolume"
abbr --add krmpv "kubectl delete persistentvolume"
abbr --add ksysrmpv "kubectl --namespace=kube-system delete persistentvolume"
abbr --add kgpvc "kubectl get persistentvolumeclaim"
abbr --add ksysgpvc "kubectl --namespace=kube-system get persistentvolumeclaim"
abbr --add kdpvc "kubectl describe persistentvolumeclaim"
abbr --add ksysdpvc "kubectl --namespace=kube-system describe persistentvolumeclaim"
abbr --add krmpvc "kubectl delete persistentvolumeclaim"
abbr --add ksysrmpvc "kubectl --namespace=kube-system delete persistentvolumeclaim"
abbr --add kgva "kubectl get volumeattachment"
abbr --add ksysgva "kubectl --namespace=kube-system get volumeattachment"
abbr --add kdva "kubectl describe volumeattachment"
abbr --add ksysdva "kubectl --namespace=kube-system describe volumeattachment"
abbr --add krmva "kubectl delete volumeattachment"
abbr --add ksysrmva "kubectl --namespace=kube-system delete volumeattachment"
abbr --add kgno "kubectl get nodes"
abbr --add kdno "kubectl describe nodes"
abbr --add krmno "kubectl delete nodes"
abbr --add kgns "kubectl get namespaces"
abbr --add kdns "kubectl describe namespaces"
abbr --add krmns "kubectl delete namespaces"
abbr --add kgoyaml "kubectl get -o=yaml"
abbr --add ksysgoyaml "kubectl --namespace=kube-system get -o=yaml"
abbr --add kgpooyaml "kubectl get pods -o=yaml"
abbr --add ksysgpooyaml "kubectl --namespace=kube-system get pods -o=yaml"
abbr --add kgdepoyaml "kubectl get deployment -o=yaml"
abbr --add ksysgdepoyaml "kubectl --namespace=kube-system get deployment -o=yaml"
abbr --add kgssoyaml "kubectl get statefulset -o=yaml"
abbr --add ksysgssoyaml "kubectl --namespace=kube-system get statefulset -o=yaml"
abbr --add kgdsoyaml "kubectl get daemonset -o=yaml"
abbr --add ksysgdsoyaml "kubectl --namespace=kube-system get daemonset -o=yaml"
abbr --add kgjoboyaml "kubectl get job -o=yaml"
abbr --add ksysgjoboyaml "kubectl --namespace=kube-system get job -o=yaml"
abbr --add kgcjoboyaml "kubectl get cronjob -o=yaml"
abbr --add ksysgcjoboyaml "kubectl --namespace=kube-system get cronjob -o=yaml"
abbr --add kgsvcoyaml "kubectl get service -o=yaml"
abbr --add ksysgsvcoyaml "kubectl --namespace=kube-system get service -o=yaml"
abbr --add kgingoyaml "kubectl get ingress -o=yaml"
abbr --add ksysgingoyaml "kubectl --namespace=kube-system get ingress -o=yaml"
abbr --add kgcmoyaml "kubectl get configmap -o=yaml"
abbr --add ksysgcmoyaml "kubectl --namespace=kube-system get configmap -o=yaml"
abbr --add kgsecoyaml "kubectl get secret -o=yaml"
abbr --add ksysgsecoyaml "kubectl --namespace=kube-system get secret -o=yaml"
abbr --add kgscoyaml "kubectl get storageclass -o=yaml"
abbr --add ksysgscoyaml "kubectl --namespace=kube-system get storageclass -o=yaml"
abbr --add kgpvoyaml "kubectl get persistentvolume -o=yaml"
abbr --add ksysgpvoyaml "kubectl --namespace=kube-system get persistentvolume -o=yaml"
abbr --add kgpvcoyaml "kubectl get persistentvolumeclaim -o=yaml"
abbr --add ksysgpvcoyaml "kubectl --namespace=kube-system get persistentvolumeclaim -o=yaml"
abbr --add kgvaoyaml "kubectl get volumeattachment -o=yaml"
abbr --add ksysgvaoyaml "kubectl --namespace=kube-system get volumeattachment -o=yaml"
abbr --add kgnooyaml "kubectl get nodes -o=yaml"
abbr --add kgnsoyaml "kubectl get namespaces -o=yaml"
abbr --add kgowide "kubectl get -o=wide"
abbr --add ksysgowide "kubectl --namespace=kube-system get -o=wide"
abbr --add kgpoowide "kubectl get pods -o=wide"
abbr --add ksysgpoowide "kubectl --namespace=kube-system get pods -o=wide"
abbr --add kgdepowide "kubectl get deployment -o=wide"
abbr --add ksysgdepowide "kubectl --namespace=kube-system get deployment -o=wide"
abbr --add kgssowide "kubectl get statefulset -o=wide"
abbr --add ksysgssowide "kubectl --namespace=kube-system get statefulset -o=wide"
abbr --add kgdsowide "kubectl get daemonset -o=wide"
abbr --add ksysgdsowide "kubectl --namespace=kube-system get daemonset -o=wide"
abbr --add kgjobowide "kubectl get job -o=wide"
abbr --add ksysgjobowide "kubectl --namespace=kube-system get job -o=wide"
abbr --add kgcjobowide "kubectl get cronjob -o=wide"
abbr --add ksysgcjobowide "kubectl --namespace=kube-system get cronjob -o=wide"
abbr --add kgsvcowide "kubectl get service -o=wide"
abbr --add ksysgsvcowide "kubectl --namespace=kube-system get service -o=wide"
abbr --add kgingowide "kubectl get ingress -o=wide"
abbr --add ksysgingowide "kubectl --namespace=kube-system get ingress -o=wide"
abbr --add kgcmowide "kubectl get configmap -o=wide"
abbr --add ksysgcmowide "kubectl --namespace=kube-system get configmap -o=wide"
abbr --add kgsecowide "kubectl get secret -o=wide"
abbr --add ksysgsecowide "kubectl --namespace=kube-system get secret -o=wide"
abbr --add kgscowide "kubectl get storageclass -o=wide"
abbr --add ksysgscowide "kubectl --namespace=kube-system get storageclass -o=wide"
abbr --add kgpvowide "kubectl get persistentvolume -o=wide"
abbr --add ksysgpvowide "kubectl --namespace=kube-system get persistentvolume -o=wide"
abbr --add kgpvcowide "kubectl get persistentvolumeclaim -o=wide"
abbr --add ksysgpvcowide "kubectl --namespace=kube-system get persistentvolumeclaim -o=wide"
abbr --add kgvaowide "kubectl get volumeattachment -o=wide"
abbr --add ksysgvaowide "kubectl --namespace=kube-system get volumeattachment -o=wide"
abbr --add kgnoowide "kubectl get nodes -o=wide"
abbr --add kgnsowide "kubectl get namespaces -o=wide"
abbr --add kgojson "kubectl get -o=json"
abbr --add ksysgojson "kubectl --namespace=kube-system get -o=json"
abbr --add kgpoojson "kubectl get pods -o=json"
abbr --add ksysgpoojson "kubectl --namespace=kube-system get pods -o=json"
abbr --add kgdepojson "kubectl get deployment -o=json"
abbr --add ksysgdepojson "kubectl --namespace=kube-system get deployment -o=json"
abbr --add kgssojson "kubectl get statefulset -o=json"
abbr --add ksysgssojson "kubectl --namespace=kube-system get statefulset -o=json"
abbr --add kgdsojson "kubectl get daemonset -o=json"
abbr --add ksysgdsojson "kubectl --namespace=kube-system get daemonset -o=json"
abbr --add kgjobojson "kubectl get job -o=json"
abbr --add ksysgjobojson "kubectl --namespace=kube-system get job -o=json"
abbr --add kgcjobojson "kubectl get cronjob -o=json"
abbr --add ksysgcjobojson "kubectl --namespace=kube-system get cronjob -o=json"
abbr --add kgsvcojson "kubectl get service -o=json"
abbr --add ksysgsvcojson "kubectl --namespace=kube-system get service -o=json"
abbr --add kgingojson "kubectl get ingress -o=json"
abbr --add ksysgingojson "kubectl --namespace=kube-system get ingress -o=json"
abbr --add kgcmojson "kubectl get configmap -o=json"
abbr --add ksysgcmojson "kubectl --namespace=kube-system get configmap -o=json"
abbr --add kgsecojson "kubectl get secret -o=json"
abbr --add ksysgsecojson "kubectl --namespace=kube-system get secret -o=json"
abbr --add kgscojson "kubectl get storageclass -o=json"
abbr --add ksysgscojson "kubectl --namespace=kube-system get storageclass -o=json"
abbr --add kgpvojson "kubectl get persistentvolume -o=json"
abbr --add ksysgpvojson "kubectl --namespace=kube-system get persistentvolume -o=json"
abbr --add kgpvcojson "kubectl get persistentvolumeclaim -o=json"
abbr --add ksysgpvcojson "kubectl --namespace=kube-system get persistentvolumeclaim -o=json"
abbr --add kgvaojson "kubectl get volumeattachment -o=json"
abbr --add ksysgvaojson "kubectl --namespace=kube-system get volumeattachment -o=json"
abbr --add kgnoojson "kubectl get nodes -o=json"
abbr --add kgnsojson "kubectl get namespaces -o=json"
abbr --add kgall "kubectl get --all-namespaces"
abbr --add kdall "kubectl describe --all-namespaces"
abbr --add kgpoall "kubectl get pods --all-namespaces"
abbr --add kdpoall "kubectl describe pods --all-namespaces"
abbr --add kgdepall "kubectl get deployment --all-namespaces"
abbr --add kddepall "kubectl describe deployment --all-namespaces"
abbr --add kgssall "kubectl get statefulset --all-namespaces"
abbr --add kdssall "kubectl describe statefulset --all-namespaces"
abbr --add kgdsall "kubectl get daemonset --all-namespaces"
abbr --add kddsall "kubectl describe daemonset --all-namespaces"
abbr --add kgjoball "kubectl get job --all-namespaces"
abbr --add kdjoball "kubectl describe job --all-namespaces"
abbr --add kgcjoball "kubectl get cronjob --all-namespaces"
abbr --add kdcjoball "kubectl describe cronjob --all-namespaces"
abbr --add kgsvcall "kubectl get service --all-namespaces"
abbr --add kdsvcall "kubectl describe service --all-namespaces"
abbr --add kgingall "kubectl get ingress --all-namespaces"
abbr --add kdingall "kubectl describe ingress --all-namespaces"
abbr --add kgcmall "kubectl get configmap --all-namespaces"
abbr --add kdcmall "kubectl describe configmap --all-namespaces"
abbr --add kgsecall "kubectl get secret --all-namespaces"
abbr --add kdsecall "kubectl describe secret --all-namespaces"
abbr --add kgscall "kubectl get storageclass --all-namespaces"
abbr --add kdscall "kubectl describe storageclass --all-namespaces"
abbr --add kgpvall "kubectl get persistentvolume --all-namespaces"
abbr --add kdpvall "kubectl describe persistentvolume --all-namespaces"
abbr --add kgpvcall "kubectl get persistentvolumeclaim --all-namespaces"
abbr --add kdpvcall "kubectl describe persistentvolumeclaim --all-namespaces"
abbr --add kgvaall "kubectl get volumeattachment --all-namespaces"
abbr --add kdvaall "kubectl describe volumeattachment --all-namespaces"
abbr --add kgsl "kubectl get --show-labels"
abbr --add ksysgsl "kubectl --namespace=kube-system get --show-labels"
abbr --add kgposl "kubectl get pods --show-labels"
abbr --add ksysgposl "kubectl --namespace=kube-system get pods --show-labels"
abbr --add kgdepsl "kubectl get deployment --show-labels"
abbr --add ksysgdepsl "kubectl --namespace=kube-system get deployment --show-labels"
abbr --add kgsssl "kubectl get statefulset --show-labels"
abbr --add ksysgsssl "kubectl --namespace=kube-system get statefulset --show-labels"
abbr --add kgdssl "kubectl get daemonset --show-labels"
abbr --add ksysgdssl "kubectl --namespace=kube-system get daemonset --show-labels"
abbr --add kgjobsl "kubectl get job --show-labels"
abbr --add ksysgjobsl "kubectl --namespace=kube-system get job --show-labels"
abbr --add kgcjobsl "kubectl get cronjob --show-labels"
abbr --add ksysgcjobsl "kubectl --namespace=kube-system get cronjob --show-labels"
abbr --add kgsvcsl "kubectl get service --show-labels"
abbr --add ksysgsvcsl "kubectl --namespace=kube-system get service --show-labels"
abbr --add kgingsl "kubectl get ingress --show-labels"
abbr --add ksysgingsl "kubectl --namespace=kube-system get ingress --show-labels"
abbr --add kgcmsl "kubectl get configmap --show-labels"
abbr --add ksysgcmsl "kubectl --namespace=kube-system get configmap --show-labels"
abbr --add kgsecsl "kubectl get secret --show-labels"
abbr --add ksysgsecsl "kubectl --namespace=kube-system get secret --show-labels"
abbr --add kgscsl "kubectl get storageclass --show-labels"
abbr --add ksysgscsl "kubectl --namespace=kube-system get storageclass --show-labels"
abbr --add kgpvsl "kubectl get persistentvolume --show-labels"
abbr --add ksysgpvsl "kubectl --namespace=kube-system get persistentvolume --show-labels"
abbr --add kgpvcsl "kubectl get persistentvolumeclaim --show-labels"
abbr --add ksysgpvcsl "kubectl --namespace=kube-system get persistentvolumeclaim --show-labels"
abbr --add kgvasl "kubectl get volumeattachment --show-labels"
abbr --add ksysgvasl "kubectl --namespace=kube-system get volumeattachment --show-labels"
abbr --add kgnosl "kubectl get nodes --show-labels"
abbr --add kgnssl "kubectl get namespaces --show-labels"
abbr --add krmall "kubectl delete --all"
abbr --add ksysrmall "kubectl --namespace=kube-system delete --all"
abbr --add krmpoall "kubectl delete pods --all"
abbr --add ksysrmpoall "kubectl --namespace=kube-system delete pods --all"
abbr --add krmdepall "kubectl delete deployment --all"
abbr --add ksysrmdepall "kubectl --namespace=kube-system delete deployment --all"
abbr --add krmssall "kubectl delete statefulset --all"
abbr --add ksysrmssall "kubectl --namespace=kube-system delete statefulset --all"
abbr --add krmdsall "kubectl delete daemonset --all"
abbr --add ksysrmdsall "kubectl --namespace=kube-system delete daemonset --all"
abbr --add krmjoball "kubectl delete job --all"
abbr --add ksysrmjoball "kubectl --namespace=kube-system delete job --all"
abbr --add krmcjoball "kubectl delete cronjob --all"
abbr --add ksysrmcjoball "kubectl --namespace=kube-system delete cronjob --all"
abbr --add krmsvcall "kubectl delete service --all"
abbr --add ksysrmsvcall "kubectl --namespace=kube-system delete service --all"
abbr --add krmingall "kubectl delete ingress --all"
abbr --add ksysrmingall "kubectl --namespace=kube-system delete ingress --all"
abbr --add krmcmall "kubectl delete configmap --all"
abbr --add ksysrmcmall "kubectl --namespace=kube-system delete configmap --all"
abbr --add krmsecall "kubectl delete secret --all"
abbr --add ksysrmsecall "kubectl --namespace=kube-system delete secret --all"
abbr --add krmscall "kubectl delete storageclass --all"
abbr --add ksysrmscall "kubectl --namespace=kube-system delete storageclass --all"
abbr --add krmpvall "kubectl delete persistentvolume --all"
abbr --add ksysrmpvall "kubectl --namespace=kube-system delete persistentvolume --all"
abbr --add krmpvcall "kubectl delete persistentvolumeclaim --all"
abbr --add ksysrmpvcall "kubectl --namespace=kube-system delete persistentvolumeclaim --all"
abbr --add krmvaall "kubectl delete volumeattachment --all"
abbr --add ksysrmvaall "kubectl --namespace=kube-system delete volumeattachment --all"
abbr --add krmnoall "kubectl delete nodes --all"
abbr --add krmnsall "kubectl delete namespaces --all"
abbr --add kgw "kubectl get --watch"
abbr --add ksysgw "kubectl --namespace=kube-system get --watch"
abbr --add kgpow "kubectl get pods --watch"
abbr --add ksysgpow "kubectl --namespace=kube-system get pods --watch"
abbr --add kgdepw "kubectl get deployment --watch"
abbr --add ksysgdepw "kubectl --namespace=kube-system get deployment --watch"
abbr --add kgssw "kubectl get statefulset --watch"
abbr --add ksysgssw "kubectl --namespace=kube-system get statefulset --watch"
abbr --add kgdsw "kubectl get daemonset --watch"
abbr --add ksysgdsw "kubectl --namespace=kube-system get daemonset --watch"
abbr --add kgjobw "kubectl get job --watch"
abbr --add ksysgjobw "kubectl --namespace=kube-system get job --watch"
abbr --add kgcjobw "kubectl get cronjob --watch"
abbr --add ksysgcjobw "kubectl --namespace=kube-system get cronjob --watch"
abbr --add kgsvcw "kubectl get service --watch"
abbr --add ksysgsvcw "kubectl --namespace=kube-system get service --watch"
abbr --add kgingw "kubectl get ingress --watch"
abbr --add ksysgingw "kubectl --namespace=kube-system get ingress --watch"
abbr --add kgcmw "kubectl get configmap --watch"
abbr --add ksysgcmw "kubectl --namespace=kube-system get configmap --watch"
abbr --add kgsecw "kubectl get secret --watch"
abbr --add ksysgsecw "kubectl --namespace=kube-system get secret --watch"
abbr --add kgscw "kubectl get storageclass --watch"
abbr --add ksysgscw "kubectl --namespace=kube-system get storageclass --watch"
abbr --add kgpvw "kubectl get persistentvolume --watch"
abbr --add ksysgpvw "kubectl --namespace=kube-system get persistentvolume --watch"
abbr --add kgpvcw "kubectl get persistentvolumeclaim --watch"
abbr --add ksysgpvcw "kubectl --namespace=kube-system get persistentvolumeclaim --watch"
abbr --add kgvaw "kubectl get volumeattachment --watch"
abbr --add ksysgvaw "kubectl --namespace=kube-system get volumeattachment --watch"
abbr --add kgnow "kubectl get nodes --watch"
abbr --add kgnsw "kubectl get namespaces --watch"
abbr --add kgoyamlall "kubectl get -o=yaml --all-namespaces"
abbr --add kgpooyamlall "kubectl get pods -o=yaml --all-namespaces"
abbr --add kgdepoyamlall "kubectl get deployment -o=yaml --all-namespaces"
abbr --add kgssoyamlall "kubectl get statefulset -o=yaml --all-namespaces"
abbr --add kgdsoyamlall "kubectl get daemonset -o=yaml --all-namespaces"
abbr --add kgjoboyamlall "kubectl get job -o=yaml --all-namespaces"
abbr --add kgcjoboyamlall "kubectl get cronjob -o=yaml --all-namespaces"
abbr --add kgsvcoyamlall "kubectl get service -o=yaml --all-namespaces"
abbr --add kgingoyamlall "kubectl get ingress -o=yaml --all-namespaces"
abbr --add kgcmoyamlall "kubectl get configmap -o=yaml --all-namespaces"
abbr --add kgsecoyamlall "kubectl get secret -o=yaml --all-namespaces"
abbr --add kgscoyamlall "kubectl get storageclass -o=yaml --all-namespaces"
abbr --add kgpvoyamlall "kubectl get persistentvolume -o=yaml --all-namespaces"
abbr --add kgpvcoyamlall "kubectl get persistentvolumeclaim -o=yaml --all-namespaces"
abbr --add kgvaoyamlall "kubectl get volumeattachment -o=yaml --all-namespaces"
abbr --add kgalloyaml "kubectl get --all-namespaces -o=yaml"
abbr --add kgpoalloyaml "kubectl get pods --all-namespaces -o=yaml"
abbr --add kgdepalloyaml "kubectl get deployment --all-namespaces -o=yaml"
abbr --add kgssalloyaml "kubectl get statefulset --all-namespaces -o=yaml"
abbr --add kgdsalloyaml "kubectl get daemonset --all-namespaces -o=yaml"
abbr --add kgjoballoyaml "kubectl get job --all-namespaces -o=yaml"
abbr --add kgcjoballoyaml "kubectl get cronjob --all-namespaces -o=yaml"
abbr --add kgsvcalloyaml "kubectl get service --all-namespaces -o=yaml"
abbr --add kgingalloyaml "kubectl get ingress --all-namespaces -o=yaml"
abbr --add kgcmalloyaml "kubectl get configmap --all-namespaces -o=yaml"
abbr --add kgsecalloyaml "kubectl get secret --all-namespaces -o=yaml"
abbr --add kgscalloyaml "kubectl get storageclass --all-namespaces -o=yaml"
abbr --add kgpvalloyaml "kubectl get persistentvolume --all-namespaces -o=yaml"
abbr --add kgpvcalloyaml "kubectl get persistentvolumeclaim --all-namespaces -o=yaml"
abbr --add kgvaalloyaml "kubectl get volumeattachment --all-namespaces -o=yaml"
abbr --add kgowideall "kubectl get -o=wide --all-namespaces"
abbr --add kgpoowideall "kubectl get pods -o=wide --all-namespaces"
abbr --add kgdepowideall "kubectl get deployment -o=wide --all-namespaces"
abbr --add kgssowideall "kubectl get statefulset -o=wide --all-namespaces"
abbr --add kgdsowideall "kubectl get daemonset -o=wide --all-namespaces"
abbr --add kgjobowideall "kubectl get job -o=wide --all-namespaces"
abbr --add kgcjobowideall "kubectl get cronjob -o=wide --all-namespaces"
abbr --add kgsvcowideall "kubectl get service -o=wide --all-namespaces"
abbr --add kgingowideall "kubectl get ingress -o=wide --all-namespaces"
abbr --add kgcmowideall "kubectl get configmap -o=wide --all-namespaces"
abbr --add kgsecowideall "kubectl get secret -o=wide --all-namespaces"
abbr --add kgscowideall "kubectl get storageclass -o=wide --all-namespaces"
abbr --add kgpvowideall "kubectl get persistentvolume -o=wide --all-namespaces"
abbr --add kgpvcowideall "kubectl get persistentvolumeclaim -o=wide --all-namespaces"
abbr --add kgvaowideall "kubectl get volumeattachment -o=wide --all-namespaces"
abbr --add kgallowide "kubectl get --all-namespaces -o=wide"
abbr --add kgpoallowide "kubectl get pods --all-namespaces -o=wide"
abbr --add kgdepallowide "kubectl get deployment --all-namespaces -o=wide"
abbr --add kgssallowide "kubectl get statefulset --all-namespaces -o=wide"
abbr --add kgdsallowide "kubectl get daemonset --all-namespaces -o=wide"
abbr --add kgjoballowide "kubectl get job --all-namespaces -o=wide"
abbr --add kgcjoballowide "kubectl get cronjob --all-namespaces -o=wide"
abbr --add kgsvcallowide "kubectl get service --all-namespaces -o=wide"
abbr --add kgingallowide "kubectl get ingress --all-namespaces -o=wide"
abbr --add kgcmallowide "kubectl get configmap --all-namespaces -o=wide"
abbr --add kgsecallowide "kubectl get secret --all-namespaces -o=wide"
abbr --add kgscallowide "kubectl get storageclass --all-namespaces -o=wide"
abbr --add kgpvallowide "kubectl get persistentvolume --all-namespaces -o=wide"
abbr --add kgpvcallowide "kubectl get persistentvolumeclaim --all-namespaces -o=wide"
abbr --add kgvaallowide "kubectl get volumeattachment --all-namespaces -o=wide"
abbr --add kgowidesl "kubectl get -o=wide --show-labels"
abbr --add ksysgowidesl "kubectl --namespace=kube-system get -o=wide --show-labels"
abbr --add kgpoowidesl "kubectl get pods -o=wide --show-labels"
abbr --add ksysgpoowidesl "kubectl --namespace=kube-system get pods -o=wide --show-labels"
abbr --add kgdepowidesl "kubectl get deployment -o=wide --show-labels"
abbr --add ksysgdepowidesl "kubectl --namespace=kube-system get deployment -o=wide --show-labels"
abbr --add kgssowidesl "kubectl get statefulset -o=wide --show-labels"
abbr --add ksysgssowidesl "kubectl --namespace=kube-system get statefulset -o=wide --show-labels"
abbr --add kgdsowidesl "kubectl get daemonset -o=wide --show-labels"
abbr --add ksysgdsowidesl "kubectl --namespace=kube-system get daemonset -o=wide --show-labels"
abbr --add kgjobowidesl "kubectl get job -o=wide --show-labels"
abbr --add ksysgjobowidesl "kubectl --namespace=kube-system get job -o=wide --show-labels"
abbr --add kgcjobowidesl "kubectl get cronjob -o=wide --show-labels"
abbr --add ksysgcjobowidesl "kubectl --namespace=kube-system get cronjob -o=wide --show-labels"
abbr --add kgsvcowidesl "kubectl get service -o=wide --show-labels"
abbr --add ksysgsvcowidesl "kubectl --namespace=kube-system get service -o=wide --show-labels"
abbr --add kgingowidesl "kubectl get ingress -o=wide --show-labels"
abbr --add ksysgingowidesl "kubectl --namespace=kube-system get ingress -o=wide --show-labels"
abbr --add kgcmowidesl "kubectl get configmap -o=wide --show-labels"
abbr --add ksysgcmowidesl "kubectl --namespace=kube-system get configmap -o=wide --show-labels"
abbr --add kgsecowidesl "kubectl get secret -o=wide --show-labels"
abbr --add ksysgsecowidesl "kubectl --namespace=kube-system get secret -o=wide --show-labels"
abbr --add kgscowidesl "kubectl get storageclass -o=wide --show-labels"
abbr --add ksysgscowidesl "kubectl --namespace=kube-system get storageclass -o=wide --show-labels"
abbr --add kgpvowidesl "kubectl get persistentvolume -o=wide --show-labels"
abbr --add ksysgpvowidesl "kubectl --namespace=kube-system get persistentvolume -o=wide --show-labels"
abbr --add kgpvcowidesl "kubectl get persistentvolumeclaim -o=wide --show-labels"
abbr --add ksysgpvcowidesl "kubectl --namespace=kube-system get persistentvolumeclaim -o=wide --show-labels"
abbr --add kgvaowidesl "kubectl get volumeattachment -o=wide --show-labels"
abbr --add ksysgvaowidesl "kubectl --namespace=kube-system get volumeattachment -o=wide --show-labels"
abbr --add kgnoowidesl "kubectl get nodes -o=wide --show-labels"
abbr --add kgnsowidesl "kubectl get namespaces -o=wide --show-labels"
abbr --add kgslowide "kubectl get --show-labels -o=wide"
abbr --add ksysgslowide "kubectl --namespace=kube-system get --show-labels -o=wide"
abbr --add kgposlowide "kubectl get pods --show-labels -o=wide"
abbr --add ksysgposlowide "kubectl --namespace=kube-system get pods --show-labels -o=wide"
abbr --add kgdepslowide "kubectl get deployment --show-labels -o=wide"
abbr --add ksysgdepslowide "kubectl --namespace=kube-system get deployment --show-labels -o=wide"
abbr --add kgssslowide "kubectl get statefulset --show-labels -o=wide"
abbr --add ksysgssslowide "kubectl --namespace=kube-system get statefulset --show-labels -o=wide"
abbr --add kgdsslowide "kubectl get daemonset --show-labels -o=wide"
abbr --add ksysgdsslowide "kubectl --namespace=kube-system get daemonset --show-labels -o=wide"
abbr --add kgjobslowide "kubectl get job --show-labels -o=wide"
abbr --add ksysgjobslowide "kubectl --namespace=kube-system get job --show-labels -o=wide"
abbr --add kgcjobslowide "kubectl get cronjob --show-labels -o=wide"
abbr --add ksysgcjobslowide "kubectl --namespace=kube-system get cronjob --show-labels -o=wide"
abbr --add kgsvcslowide "kubectl get service --show-labels -o=wide"
abbr --add ksysgsvcslowide "kubectl --namespace=kube-system get service --show-labels -o=wide"
abbr --add kgingslowide "kubectl get ingress --show-labels -o=wide"
abbr --add ksysgingslowide "kubectl --namespace=kube-system get ingress --show-labels -o=wide"
abbr --add kgcmslowide "kubectl get configmap --show-labels -o=wide"
abbr --add ksysgcmslowide "kubectl --namespace=kube-system get configmap --show-labels -o=wide"
abbr --add kgsecslowide "kubectl get secret --show-labels -o=wide"
abbr --add ksysgsecslowide "kubectl --namespace=kube-system get secret --show-labels -o=wide"
abbr --add kgscslowide "kubectl get storageclass --show-labels -o=wide"
abbr --add ksysgscslowide "kubectl --namespace=kube-system get storageclass --show-labels -o=wide"
abbr --add kgpvslowide "kubectl get persistentvolume --show-labels -o=wide"
abbr --add ksysgpvslowide "kubectl --namespace=kube-system get persistentvolume --show-labels -o=wide"
abbr --add kgpvcslowide "kubectl get persistentvolumeclaim --show-labels -o=wide"
abbr --add ksysgpvcslowide "kubectl --namespace=kube-system get persistentvolumeclaim --show-labels -o=wide"
abbr --add kgvaslowide "kubectl get volumeattachment --show-labels -o=wide"
abbr --add ksysgvaslowide "kubectl --namespace=kube-system get volumeattachment --show-labels -o=wide"
abbr --add kgnoslowide "kubectl get nodes --show-labels -o=wide"
abbr --add kgnsslowide "kubectl get namespaces --show-labels -o=wide"
abbr --add kgojsonall "kubectl get -o=json --all-namespaces"
abbr --add kgpoojsonall "kubectl get pods -o=json --all-namespaces"
abbr --add kgdepojsonall "kubectl get deployment -o=json --all-namespaces"
abbr --add kgssojsonall "kubectl get statefulset -o=json --all-namespaces"
abbr --add kgdsojsonall "kubectl get daemonset -o=json --all-namespaces"
abbr --add kgjobojsonall "kubectl get job -o=json --all-namespaces"
abbr --add kgcjobojsonall "kubectl get cronjob -o=json --all-namespaces"
abbr --add kgsvcojsonall "kubectl get service -o=json --all-namespaces"
abbr --add kgingojsonall "kubectl get ingress -o=json --all-namespaces"
abbr --add kgcmojsonall "kubectl get configmap -o=json --all-namespaces"
abbr --add kgsecojsonall "kubectl get secret -o=json --all-namespaces"
abbr --add kgscojsonall "kubectl get storageclass -o=json --all-namespaces"
abbr --add kgpvojsonall "kubectl get persistentvolume -o=json --all-namespaces"
abbr --add kgpvcojsonall "kubectl get persistentvolumeclaim -o=json --all-namespaces"
abbr --add kgvaojsonall "kubectl get volumeattachment -o=json --all-namespaces"
abbr --add kgallojson "kubectl get --all-namespaces -o=json"
abbr --add kgpoallojson "kubectl get pods --all-namespaces -o=json"
abbr --add kgdepallojson "kubectl get deployment --all-namespaces -o=json"
abbr --add kgssallojson "kubectl get statefulset --all-namespaces -o=json"
abbr --add kgdsallojson "kubectl get daemonset --all-namespaces -o=json"
abbr --add kgjoballojson "kubectl get job --all-namespaces -o=json"
abbr --add kgcjoballojson "kubectl get cronjob --all-namespaces -o=json"
abbr --add kgsvcallojson "kubectl get service --all-namespaces -o=json"
abbr --add kgingallojson "kubectl get ingress --all-namespaces -o=json"
abbr --add kgcmallojson "kubectl get configmap --all-namespaces -o=json"
abbr --add kgsecallojson "kubectl get secret --all-namespaces -o=json"
abbr --add kgscallojson "kubectl get storageclass --all-namespaces -o=json"
abbr --add kgpvallojson "kubectl get persistentvolume --all-namespaces -o=json"
abbr --add kgpvcallojson "kubectl get persistentvolumeclaim --all-namespaces -o=json"
abbr --add kgvaallojson "kubectl get volumeattachment --all-namespaces -o=json"
abbr --add kgallsl "kubectl get --all-namespaces --show-labels"
abbr --add kgpoallsl "kubectl get pods --all-namespaces --show-labels"
abbr --add kgdepallsl "kubectl get deployment --all-namespaces --show-labels"
abbr --add kgssallsl "kubectl get statefulset --all-namespaces --show-labels"
abbr --add kgdsallsl "kubectl get daemonset --all-namespaces --show-labels"
abbr --add kgjoballsl "kubectl get job --all-namespaces --show-labels"
abbr --add kgcjoballsl "kubectl get cronjob --all-namespaces --show-labels"
abbr --add kgsvcallsl "kubectl get service --all-namespaces --show-labels"
abbr --add kgingallsl "kubectl get ingress --all-namespaces --show-labels"
abbr --add kgcmallsl "kubectl get configmap --all-namespaces --show-labels"
abbr --add kgsecallsl "kubectl get secret --all-namespaces --show-labels"
abbr --add kgscallsl "kubectl get storageclass --all-namespaces --show-labels"
abbr --add kgpvallsl "kubectl get persistentvolume --all-namespaces --show-labels"
abbr --add kgpvcallsl "kubectl get persistentvolumeclaim --all-namespaces --show-labels"
abbr --add kgvaallsl "kubectl get volumeattachment --all-namespaces --show-labels"
abbr --add kgslall "kubectl get --show-labels --all-namespaces"
abbr --add kgposlall "kubectl get pods --show-labels --all-namespaces"
abbr --add kgdepslall "kubectl get deployment --show-labels --all-namespaces"
abbr --add kgssslall "kubectl get statefulset --show-labels --all-namespaces"
abbr --add kgdsslall "kubectl get daemonset --show-labels --all-namespaces"
abbr --add kgjobslall "kubectl get job --show-labels --all-namespaces"
abbr --add kgcjobslall "kubectl get cronjob --show-labels --all-namespaces"
abbr --add kgsvcslall "kubectl get service --show-labels --all-namespaces"
abbr --add kgingslall "kubectl get ingress --show-labels --all-namespaces"
abbr --add kgcmslall "kubectl get configmap --show-labels --all-namespaces"
abbr --add kgsecslall "kubectl get secret --show-labels --all-namespaces"
abbr --add kgscslall "kubectl get storageclass --show-labels --all-namespaces"
abbr --add kgpvslall "kubectl get persistentvolume --show-labels --all-namespaces"
abbr --add kgpvcslall "kubectl get persistentvolumeclaim --show-labels --all-namespaces"
abbr --add kgvaslall "kubectl get volumeattachment --show-labels --all-namespaces"
abbr --add kgallw "kubectl get --all-namespaces --watch"
abbr --add kgpoallw "kubectl get pods --all-namespaces --watch"
abbr --add kgdepallw "kubectl get deployment --all-namespaces --watch"
abbr --add kgssallw "kubectl get statefulset --all-namespaces --watch"
abbr --add kgdsallw "kubectl get daemonset --all-namespaces --watch"
abbr --add kgjoballw "kubectl get job --all-namespaces --watch"
abbr --add kgcjoballw "kubectl get cronjob --all-namespaces --watch"
abbr --add kgsvcallw "kubectl get service --all-namespaces --watch"
abbr --add kgingallw "kubectl get ingress --all-namespaces --watch"
abbr --add kgcmallw "kubectl get configmap --all-namespaces --watch"
abbr --add kgsecallw "kubectl get secret --all-namespaces --watch"
abbr --add kgscallw "kubectl get storageclass --all-namespaces --watch"
abbr --add kgpvallw "kubectl get persistentvolume --all-namespaces --watch"
abbr --add kgpvcallw "kubectl get persistentvolumeclaim --all-namespaces --watch"
abbr --add kgvaallw "kubectl get volumeattachment --all-namespaces --watch"
abbr --add kgwall "kubectl get --watch --all-namespaces"
abbr --add kgpowall "kubectl get pods --watch --all-namespaces"
abbr --add kgdepwall "kubectl get deployment --watch --all-namespaces"
abbr --add kgsswall "kubectl get statefulset --watch --all-namespaces"
abbr --add kgdswall "kubectl get daemonset --watch --all-namespaces"
abbr --add kgjobwall "kubectl get job --watch --all-namespaces"
abbr --add kgcjobwall "kubectl get cronjob --watch --all-namespaces"
abbr --add kgsvcwall "kubectl get service --watch --all-namespaces"
abbr --add kgingwall "kubectl get ingress --watch --all-namespaces"
abbr --add kgcmwall "kubectl get configmap --watch --all-namespaces"
abbr --add kgsecwall "kubectl get secret --watch --all-namespaces"
abbr --add kgscwall "kubectl get storageclass --watch --all-namespaces"
abbr --add kgpvwall "kubectl get persistentvolume --watch --all-namespaces"
abbr --add kgpvcwall "kubectl get persistentvolumeclaim --watch --all-namespaces"
abbr --add kgvawall "kubectl get volumeattachment --watch --all-namespaces"
abbr --add kgslw "kubectl get --show-labels --watch"
abbr --add ksysgslw "kubectl --namespace=kube-system get --show-labels --watch"
abbr --add kgposlw "kubectl get pods --show-labels --watch"
abbr --add ksysgposlw "kubectl --namespace=kube-system get pods --show-labels --watch"
abbr --add kgdepslw "kubectl get deployment --show-labels --watch"
abbr --add ksysgdepslw "kubectl --namespace=kube-system get deployment --show-labels --watch"
abbr --add kgssslw "kubectl get statefulset --show-labels --watch"
abbr --add ksysgssslw "kubectl --namespace=kube-system get statefulset --show-labels --watch"
abbr --add kgdsslw "kubectl get daemonset --show-labels --watch"
abbr --add ksysgdsslw "kubectl --namespace=kube-system get daemonset --show-labels --watch"
abbr --add kgjobslw "kubectl get job --show-labels --watch"
abbr --add ksysgjobslw "kubectl --namespace=kube-system get job --show-labels --watch"
abbr --add kgcjobslw "kubectl get cronjob --show-labels --watch"
abbr --add ksysgcjobslw "kubectl --namespace=kube-system get cronjob --show-labels --watch"
abbr --add kgsvcslw "kubectl get service --show-labels --watch"
abbr --add ksysgsvcslw "kubectl --namespace=kube-system get service --show-labels --watch"
abbr --add kgingslw "kubectl get ingress --show-labels --watch"
abbr --add ksysgingslw "kubectl --namespace=kube-system get ingress --show-labels --watch"
abbr --add kgcmslw "kubectl get configmap --show-labels --watch"
abbr --add ksysgcmslw "kubectl --namespace=kube-system get configmap --show-labels --watch"
abbr --add kgsecslw "kubectl get secret --show-labels --watch"
abbr --add ksysgsecslw "kubectl --namespace=kube-system get secret --show-labels --watch"
abbr --add kgscslw "kubectl get storageclass --show-labels --watch"
abbr --add ksysgscslw "kubectl --namespace=kube-system get storageclass --show-labels --watch"
abbr --add kgpvslw "kubectl get persistentvolume --show-labels --watch"
abbr --add ksysgpvslw "kubectl --namespace=kube-system get persistentvolume --show-labels --watch"
abbr --add kgpvcslw "kubectl get persistentvolumeclaim --show-labels --watch"
abbr --add ksysgpvcslw "kubectl --namespace=kube-system get persistentvolumeclaim --show-labels --watch"
abbr --add kgvaslw "kubectl get volumeattachment --show-labels --watch"
abbr --add ksysgvaslw "kubectl --namespace=kube-system get volumeattachment --show-labels --watch"
abbr --add kgnoslw "kubectl get nodes --show-labels --watch"
abbr --add kgnsslw "kubectl get namespaces --show-labels --watch"
abbr --add kgwsl "kubectl get --watch --show-labels"
abbr --add ksysgwsl "kubectl --namespace=kube-system get --watch --show-labels"
abbr --add kgpowsl "kubectl get pods --watch --show-labels"
abbr --add ksysgpowsl "kubectl --namespace=kube-system get pods --watch --show-labels"
abbr --add kgdepwsl "kubectl get deployment --watch --show-labels"
abbr --add ksysgdepwsl "kubectl --namespace=kube-system get deployment --watch --show-labels"
abbr --add kgsswsl "kubectl get statefulset --watch --show-labels"
abbr --add ksysgsswsl "kubectl --namespace=kube-system get statefulset --watch --show-labels"
abbr --add kgdswsl "kubectl get daemonset --watch --show-labels"
abbr --add ksysgdswsl "kubectl --namespace=kube-system get daemonset --watch --show-labels"
abbr --add kgjobwsl "kubectl get job --watch --show-labels"
abbr --add ksysgjobwsl "kubectl --namespace=kube-system get job --watch --show-labels"
abbr --add kgcjobwsl "kubectl get cronjob --watch --show-labels"
abbr --add ksysgcjobwsl "kubectl --namespace=kube-system get cronjob --watch --show-labels"
abbr --add kgsvcwsl "kubectl get service --watch --show-labels"
abbr --add ksysgsvcwsl "kubectl --namespace=kube-system get service --watch --show-labels"
abbr --add kgingwsl "kubectl get ingress --watch --show-labels"
abbr --add ksysgingwsl "kubectl --namespace=kube-system get ingress --watch --show-labels"
abbr --add kgcmwsl "kubectl get configmap --watch --show-labels"
abbr --add ksysgcmwsl "kubectl --namespace=kube-system get configmap --watch --show-labels"
abbr --add kgsecwsl "kubectl get secret --watch --show-labels"
abbr --add ksysgsecwsl "kubectl --namespace=kube-system get secret --watch --show-labels"
abbr --add kgscwsl "kubectl get storageclass --watch --show-labels"
abbr --add ksysgscwsl "kubectl --namespace=kube-system get storageclass --watch --show-labels"
abbr --add kgpvwsl "kubectl get persistentvolume --watch --show-labels"
abbr --add ksysgpvwsl "kubectl --namespace=kube-system get persistentvolume --watch --show-labels"
abbr --add kgpvcwsl "kubectl get persistentvolumeclaim --watch --show-labels"
abbr --add ksysgpvcwsl "kubectl --namespace=kube-system get persistentvolumeclaim --watch --show-labels"
abbr --add kgvawsl "kubectl get volumeattachment --watch --show-labels"
abbr --add ksysgvawsl "kubectl --namespace=kube-system get volumeattachment --watch --show-labels"
abbr --add kgnowsl "kubectl get nodes --watch --show-labels"
abbr --add kgnswsl "kubectl get namespaces --watch --show-labels"
abbr --add kgowideallsl "kubectl get -o=wide --all-namespaces --show-labels"
abbr --add kgpoowideallsl "kubectl get pods -o=wide --all-namespaces --show-labels"
abbr --add kgdepowideallsl "kubectl get deployment -o=wide --all-namespaces --show-labels"
abbr --add kgssowideallsl "kubectl get statefulset -o=wide --all-namespaces --show-labels"
abbr --add kgdsowideallsl "kubectl get daemonset -o=wide --all-namespaces --show-labels"
abbr --add kgjobowideallsl "kubectl get job -o=wide --all-namespaces --show-labels"
abbr --add kgcjobowideallsl "kubectl get cronjob -o=wide --all-namespaces --show-labels"
abbr --add kgsvcowideallsl "kubectl get service -o=wide --all-namespaces --show-labels"
abbr --add kgingowideallsl "kubectl get ingress -o=wide --all-namespaces --show-labels"
abbr --add kgcmowideallsl "kubectl get configmap -o=wide --all-namespaces --show-labels"
abbr --add kgsecowideallsl "kubectl get secret -o=wide --all-namespaces --show-labels"
abbr --add kgscowideallsl "kubectl get storageclass -o=wide --all-namespaces --show-labels"
abbr --add kgpvowideallsl "kubectl get persistentvolume -o=wide --all-namespaces --show-labels"
abbr --add kgpvcowideallsl "kubectl get persistentvolumeclaim -o=wide --all-namespaces --show-labels"
abbr --add kgvaowideallsl "kubectl get volumeattachment -o=wide --all-namespaces --show-labels"
abbr --add kgowideslall "kubectl get -o=wide --show-labels --all-namespaces"
abbr --add kgpoowideslall "kubectl get pods -o=wide --show-labels --all-namespaces"
abbr --add kgdepowideslall "kubectl get deployment -o=wide --show-labels --all-namespaces"
abbr --add kgssowideslall "kubectl get statefulset -o=wide --show-labels --all-namespaces"
abbr --add kgdsowideslall "kubectl get daemonset -o=wide --show-labels --all-namespaces"
abbr --add kgjobowideslall "kubectl get job -o=wide --show-labels --all-namespaces"
abbr --add kgcjobowideslall "kubectl get cronjob -o=wide --show-labels --all-namespaces"
abbr --add kgsvcowideslall "kubectl get service -o=wide --show-labels --all-namespaces"
abbr --add kgingowideslall "kubectl get ingress -o=wide --show-labels --all-namespaces"
abbr --add kgcmowideslall "kubectl get configmap -o=wide --show-labels --all-namespaces"
abbr --add kgsecowideslall "kubectl get secret -o=wide --show-labels --all-namespaces"
abbr --add kgscowideslall "kubectl get storageclass -o=wide --show-labels --all-namespaces"
abbr --add kgpvowideslall "kubectl get persistentvolume -o=wide --show-labels --all-namespaces"
abbr --add kgpvcowideslall "kubectl get persistentvolumeclaim -o=wide --show-labels --all-namespaces"
abbr --add kgvaowideslall "kubectl get volumeattachment -o=wide --show-labels --all-namespaces"
abbr --add kgallowidesl "kubectl get --all-namespaces -o=wide --show-labels"
abbr --add kgpoallowidesl "kubectl get pods --all-namespaces -o=wide --show-labels"
abbr --add kgdepallowidesl "kubectl get deployment --all-namespaces -o=wide --show-labels"
abbr --add kgssallowidesl "kubectl get statefulset --all-namespaces -o=wide --show-labels"
abbr --add kgdsallowidesl "kubectl get daemonset --all-namespaces -o=wide --show-labels"
abbr --add kgjoballowidesl "kubectl get job --all-namespaces -o=wide --show-labels"
abbr --add kgcjoballowidesl "kubectl get cronjob --all-namespaces -o=wide --show-labels"
abbr --add kgsvcallowidesl "kubectl get service --all-namespaces -o=wide --show-labels"
abbr --add kgingallowidesl "kubectl get ingress --all-namespaces -o=wide --show-labels"
abbr --add kgcmallowidesl "kubectl get configmap --all-namespaces -o=wide --show-labels"
abbr --add kgsecallowidesl "kubectl get secret --all-namespaces -o=wide --show-labels"
abbr --add kgscallowidesl "kubectl get storageclass --all-namespaces -o=wide --show-labels"
abbr --add kgpvallowidesl "kubectl get persistentvolume --all-namespaces -o=wide --show-labels"
abbr --add kgpvcallowidesl "kubectl get persistentvolumeclaim --all-namespaces -o=wide --show-labels"
abbr --add kgvaallowidesl "kubectl get volumeattachment --all-namespaces -o=wide --show-labels"
abbr --add kgallslowide "kubectl get --all-namespaces --show-labels -o=wide"
abbr --add kgpoallslowide "kubectl get pods --all-namespaces --show-labels -o=wide"
abbr --add kgdepallslowide "kubectl get deployment --all-namespaces --show-labels -o=wide"
abbr --add kgssallslowide "kubectl get statefulset --all-namespaces --show-labels -o=wide"
abbr --add kgdsallslowide "kubectl get daemonset --all-namespaces --show-labels -o=wide"
abbr --add kgjoballslowide "kubectl get job --all-namespaces --show-labels -o=wide"
abbr --add kgcjoballslowide "kubectl get cronjob --all-namespaces --show-labels -o=wide"
abbr --add kgsvcallslowide "kubectl get service --all-namespaces --show-labels -o=wide"
abbr --add kgingallslowide "kubectl get ingress --all-namespaces --show-labels -o=wide"
abbr --add kgcmallslowide "kubectl get configmap --all-namespaces --show-labels -o=wide"
abbr --add kgsecallslowide "kubectl get secret --all-namespaces --show-labels -o=wide"
abbr --add kgscallslowide "kubectl get storageclass --all-namespaces --show-labels -o=wide"
abbr --add kgpvallslowide "kubectl get persistentvolume --all-namespaces --show-labels -o=wide"
abbr --add kgpvcallslowide "kubectl get persistentvolumeclaim --all-namespaces --show-labels -o=wide"
abbr --add kgvaallslowide "kubectl get volumeattachment --all-namespaces --show-labels -o=wide"
abbr --add kgslowideall "kubectl get --show-labels -o=wide --all-namespaces"
abbr --add kgposlowideall "kubectl get pods --show-labels -o=wide --all-namespaces"
abbr --add kgdepslowideall "kubectl get deployment --show-labels -o=wide --all-namespaces"
abbr --add kgssslowideall "kubectl get statefulset --show-labels -o=wide --all-namespaces"
abbr --add kgdsslowideall "kubectl get daemonset --show-labels -o=wide --all-namespaces"
abbr --add kgjobslowideall "kubectl get job --show-labels -o=wide --all-namespaces"
abbr --add kgcjobslowideall "kubectl get cronjob --show-labels -o=wide --all-namespaces"
abbr --add kgsvcslowideall "kubectl get service --show-labels -o=wide --all-namespaces"
abbr --add kgingslowideall "kubectl get ingress --show-labels -o=wide --all-namespaces"
abbr --add kgcmslowideall "kubectl get configmap --show-labels -o=wide --all-namespaces"
abbr --add kgsecslowideall "kubectl get secret --show-labels -o=wide --all-namespaces"
abbr --add kgscslowideall "kubectl get storageclass --show-labels -o=wide --all-namespaces"
abbr --add kgpvslowideall "kubectl get persistentvolume --show-labels -o=wide --all-namespaces"
abbr --add kgpvcslowideall "kubectl get persistentvolumeclaim --show-labels -o=wide --all-namespaces"
abbr --add kgvaslowideall "kubectl get volumeattachment --show-labels -o=wide --all-namespaces"
abbr --add kgslallowide "kubectl get --show-labels --all-namespaces -o=wide"
abbr --add kgposlallowide "kubectl get pods --show-labels --all-namespaces -o=wide"
abbr --add kgdepslallowide "kubectl get deployment --show-labels --all-namespaces -o=wide"
abbr --add kgssslallowide "kubectl get statefulset --show-labels --all-namespaces -o=wide"
abbr --add kgdsslallowide "kubectl get daemonset --show-labels --all-namespaces -o=wide"
abbr --add kgjobslallowide "kubectl get job --show-labels --all-namespaces -o=wide"
abbr --add kgcjobslallowide "kubectl get cronjob --show-labels --all-namespaces -o=wide"
abbr --add kgsvcslallowide "kubectl get service --show-labels --all-namespaces -o=wide"
abbr --add kgingslallowide "kubectl get ingress --show-labels --all-namespaces -o=wide"
abbr --add kgcmslallowide "kubectl get configmap --show-labels --all-namespaces -o=wide"
abbr --add kgsecslallowide "kubectl get secret --show-labels --all-namespaces -o=wide"
abbr --add kgscslallowide "kubectl get storageclass --show-labels --all-namespaces -o=wide"
abbr --add kgpvslallowide "kubectl get persistentvolume --show-labels --all-namespaces -o=wide"
abbr --add kgpvcslallowide "kubectl get persistentvolumeclaim --show-labels --all-namespaces -o=wide"
abbr --add kgvaslallowide "kubectl get volumeattachment --show-labels --all-namespaces -o=wide"
abbr --add kgallslw "kubectl get --all-namespaces --show-labels --watch"
abbr --add kgpoallslw "kubectl get pods --all-namespaces --show-labels --watch"
abbr --add kgdepallslw "kubectl get deployment --all-namespaces --show-labels --watch"
abbr --add kgssallslw "kubectl get statefulset --all-namespaces --show-labels --watch"
abbr --add kgdsallslw "kubectl get daemonset --all-namespaces --show-labels --watch"
abbr --add kgjoballslw "kubectl get job --all-namespaces --show-labels --watch"
abbr --add kgcjoballslw "kubectl get cronjob --all-namespaces --show-labels --watch"
abbr --add kgsvcallslw "kubectl get service --all-namespaces --show-labels --watch"
abbr --add kgingallslw "kubectl get ingress --all-namespaces --show-labels --watch"
abbr --add kgcmallslw "kubectl get configmap --all-namespaces --show-labels --watch"
abbr --add kgsecallslw "kubectl get secret --all-namespaces --show-labels --watch"
abbr --add kgscallslw "kubectl get storageclass --all-namespaces --show-labels --watch"
abbr --add kgpvallslw "kubectl get persistentvolume --all-namespaces --show-labels --watch"
abbr --add kgpvcallslw "kubectl get persistentvolumeclaim --all-namespaces --show-labels --watch"
abbr --add kgvaallslw "kubectl get volumeattachment --all-namespaces --show-labels --watch"
abbr --add kgallwsl "kubectl get --all-namespaces --watch --show-labels"
abbr --add kgpoallwsl "kubectl get pods --all-namespaces --watch --show-labels"
abbr --add kgdepallwsl "kubectl get deployment --all-namespaces --watch --show-labels"
abbr --add kgssallwsl "kubectl get statefulset --all-namespaces --watch --show-labels"
abbr --add kgdsallwsl "kubectl get daemonset --all-namespaces --watch --show-labels"
abbr --add kgjoballwsl "kubectl get job --all-namespaces --watch --show-labels"
abbr --add kgcjoballwsl "kubectl get cronjob --all-namespaces --watch --show-labels"
abbr --add kgsvcallwsl "kubectl get service --all-namespaces --watch --show-labels"
abbr --add kgingallwsl "kubectl get ingress --all-namespaces --watch --show-labels"
abbr --add kgcmallwsl "kubectl get configmap --all-namespaces --watch --show-labels"
abbr --add kgsecallwsl "kubectl get secret --all-namespaces --watch --show-labels"
abbr --add kgscallwsl "kubectl get storageclass --all-namespaces --watch --show-labels"
abbr --add kgpvallwsl "kubectl get persistentvolume --all-namespaces --watch --show-labels"
abbr --add kgpvcallwsl "kubectl get persistentvolumeclaim --all-namespaces --watch --show-labels"
abbr --add kgvaallwsl "kubectl get volumeattachment --all-namespaces --watch --show-labels"
abbr --add kgslallw "kubectl get --show-labels --all-namespaces --watch"
abbr --add kgposlallw "kubectl get pods --show-labels --all-namespaces --watch"
abbr --add kgdepslallw "kubectl get deployment --show-labels --all-namespaces --watch"
abbr --add kgssslallw "kubectl get statefulset --show-labels --all-namespaces --watch"
abbr --add kgdsslallw "kubectl get daemonset --show-labels --all-namespaces --watch"
abbr --add kgjobslallw "kubectl get job --show-labels --all-namespaces --watch"
abbr --add kgcjobslallw "kubectl get cronjob --show-labels --all-namespaces --watch"
abbr --add kgsvcslallw "kubectl get service --show-labels --all-namespaces --watch"
abbr --add kgingslallw "kubectl get ingress --show-labels --all-namespaces --watch"
abbr --add kgcmslallw "kubectl get configmap --show-labels --all-namespaces --watch"
abbr --add kgsecslallw "kubectl get secret --show-labels --all-namespaces --watch"
abbr --add kgscslallw "kubectl get storageclass --show-labels --all-namespaces --watch"
abbr --add kgpvslallw "kubectl get persistentvolume --show-labels --all-namespaces --watch"
abbr --add kgpvcslallw "kubectl get persistentvolumeclaim --show-labels --all-namespaces --watch"
abbr --add kgvaslallw "kubectl get volumeattachment --show-labels --all-namespaces --watch"
abbr --add kgslwall "kubectl get --show-labels --watch --all-namespaces"
abbr --add kgposlwall "kubectl get pods --show-labels --watch --all-namespaces"
abbr --add kgdepslwall "kubectl get deployment --show-labels --watch --all-namespaces"
abbr --add kgssslwall "kubectl get statefulset --show-labels --watch --all-namespaces"
abbr --add kgdsslwall "kubectl get daemonset --show-labels --watch --all-namespaces"
abbr --add kgjobslwall "kubectl get job --show-labels --watch --all-namespaces"
abbr --add kgcjobslwall "kubectl get cronjob --show-labels --watch --all-namespaces"
abbr --add kgsvcslwall "kubectl get service --show-labels --watch --all-namespaces"
abbr --add kgingslwall "kubectl get ingress --show-labels --watch --all-namespaces"
abbr --add kgcmslwall "kubectl get configmap --show-labels --watch --all-namespaces"
abbr --add kgsecslwall "kubectl get secret --show-labels --watch --all-namespaces"
abbr --add kgscslwall "kubectl get storageclass --show-labels --watch --all-namespaces"
abbr --add kgpvslwall "kubectl get persistentvolume --show-labels --watch --all-namespaces"
abbr --add kgpvcslwall "kubectl get persistentvolumeclaim --show-labels --watch --all-namespaces"
abbr --add kgvaslwall "kubectl get volumeattachment --show-labels --watch --all-namespaces"
abbr --add kgwallsl "kubectl get --watch --all-namespaces --show-labels"
abbr --add kgpowallsl "kubectl get pods --watch --all-namespaces --show-labels"
abbr --add kgdepwallsl "kubectl get deployment --watch --all-namespaces --show-labels"
abbr --add kgsswallsl "kubectl get statefulset --watch --all-namespaces --show-labels"
abbr --add kgdswallsl "kubectl get daemonset --watch --all-namespaces --show-labels"
abbr --add kgjobwallsl "kubectl get job --watch --all-namespaces --show-labels"
abbr --add kgcjobwallsl "kubectl get cronjob --watch --all-namespaces --show-labels"
abbr --add kgsvcwallsl "kubectl get service --watch --all-namespaces --show-labels"
abbr --add kgingwallsl "kubectl get ingress --watch --all-namespaces --show-labels"
abbr --add kgcmwallsl "kubectl get configmap --watch --all-namespaces --show-labels"
abbr --add kgsecwallsl "kubectl get secret --watch --all-namespaces --show-labels"
abbr --add kgscwallsl "kubectl get storageclass --watch --all-namespaces --show-labels"
abbr --add kgpvwallsl "kubectl get persistentvolume --watch --all-namespaces --show-labels"
abbr --add kgpvcwallsl "kubectl get persistentvolumeclaim --watch --all-namespaces --show-labels"
abbr --add kgvawallsl "kubectl get volumeattachment --watch --all-namespaces --show-labels"
abbr --add kgwslall "kubectl get --watch --show-labels --all-namespaces"
abbr --add kgpowslall "kubectl get pods --watch --show-labels --all-namespaces"
abbr --add kgdepwslall "kubectl get deployment --watch --show-labels --all-namespaces"
abbr --add kgsswslall "kubectl get statefulset --watch --show-labels --all-namespaces"
abbr --add kgdswslall "kubectl get daemonset --watch --show-labels --all-namespaces"
abbr --add kgjobwslall "kubectl get job --watch --show-labels --all-namespaces"
abbr --add kgcjobwslall "kubectl get cronjob --watch --show-labels --all-namespaces"
abbr --add kgsvcwslall "kubectl get service --watch --show-labels --all-namespaces"
abbr --add kgingwslall "kubectl get ingress --watch --show-labels --all-namespaces"
abbr --add kgcmwslall "kubectl get configmap --watch --show-labels --all-namespaces"
abbr --add kgsecwslall "kubectl get secret --watch --show-labels --all-namespaces"
abbr --add kgscwslall "kubectl get storageclass --watch --show-labels --all-namespaces"
abbr --add kgpvwslall "kubectl get persistentvolume --watch --show-labels --all-namespaces"
abbr --add kgpvcwslall "kubectl get persistentvolumeclaim --watch --show-labels --all-namespaces"
abbr --add kgvawslall "kubectl get volumeattachment --watch --show-labels --all-namespaces"
abbr --add kgf "kubectl get --recursive -f"
abbr --add kdf "kubectl describe --recursive -f"
abbr --add krmf "kubectl delete --recursive -f"
abbr --add kgoyamlf "kubectl get -o=yaml --recursive -f"
abbr --add kgowidef "kubectl get -o=wide --recursive -f"
abbr --add kgojsonf "kubectl get -o=json --recursive -f"
abbr --add kgslf "kubectl get --show-labels --recursive -f"
abbr --add kgwf "kubectl get --watch --recursive -f"
abbr --add kgowideslf "kubectl get -o=wide --show-labels --recursive -f"
abbr --add kgslowidef "kubectl get --show-labels -o=wide --recursive -f"
abbr --add kgslwf "kubectl get --show-labels --watch --recursive -f"
abbr --add kgwslf "kubectl get --watch --show-labels --recursive -f"
abbr --add kgl "kubectl get -l"
abbr --add ksysgl "kubectl --namespace=kube-system get -l"
abbr --add kdl "kubectl describe -l"
abbr --add ksysdl "kubectl --namespace=kube-system describe -l"
abbr --add krml "kubectl delete -l"
abbr --add ksysrml "kubectl --namespace=kube-system delete -l"
abbr --add kgpol "kubectl get pods -l"
abbr --add ksysgpol "kubectl --namespace=kube-system get pods -l"
abbr --add kdpol "kubectl describe pods -l"
abbr --add ksysdpol "kubectl --namespace=kube-system describe pods -l"
abbr --add krmpol "kubectl delete pods -l"
abbr --add ksysrmpol "kubectl --namespace=kube-system delete pods -l"
abbr --add kgdepl "kubectl get deployment -l"
abbr --add ksysgdepl "kubectl --namespace=kube-system get deployment -l"
abbr --add kddepl "kubectl describe deployment -l"
abbr --add ksysddepl "kubectl --namespace=kube-system describe deployment -l"
abbr --add krmdepl "kubectl delete deployment -l"
abbr --add ksysrmdepl "kubectl --namespace=kube-system delete deployment -l"
abbr --add kgssl "kubectl get statefulset -l"
abbr --add ksysgssl "kubectl --namespace=kube-system get statefulset -l"
abbr --add kdssl "kubectl describe statefulset -l"
abbr --add ksysdssl "kubectl --namespace=kube-system describe statefulset -l"
abbr --add krmssl "kubectl delete statefulset -l"
abbr --add ksysrmssl "kubectl --namespace=kube-system delete statefulset -l"
abbr --add kgdsl "kubectl get daemonset -l"
abbr --add ksysgdsl "kubectl --namespace=kube-system get daemonset -l"
abbr --add kddsl "kubectl describe daemonset -l"
abbr --add ksysddsl "kubectl --namespace=kube-system describe daemonset -l"
abbr --add krmdsl "kubectl delete daemonset -l"
abbr --add ksysrmdsl "kubectl --namespace=kube-system delete daemonset -l"
abbr --add kgjobl "kubectl get job -l"
abbr --add ksysgjobl "kubectl --namespace=kube-system get job -l"
abbr --add kdjobl "kubectl describe job -l"
abbr --add ksysdjobl "kubectl --namespace=kube-system describe job -l"
abbr --add krmjobl "kubectl delete job -l"
abbr --add ksysrmjobl "kubectl --namespace=kube-system delete job -l"
abbr --add kgcjobl "kubectl get cronjob -l"
abbr --add ksysgcjobl "kubectl --namespace=kube-system get cronjob -l"
abbr --add kdcjobl "kubectl describe cronjob -l"
abbr --add ksysdcjobl "kubectl --namespace=kube-system describe cronjob -l"
abbr --add krmcjobl "kubectl delete cronjob -l"
abbr --add ksysrmcjobl "kubectl --namespace=kube-system delete cronjob -l"
abbr --add kgsvcl "kubectl get service -l"
abbr --add ksysgsvcl "kubectl --namespace=kube-system get service -l"
abbr --add kdsvcl "kubectl describe service -l"
abbr --add ksysdsvcl "kubectl --namespace=kube-system describe service -l"
abbr --add krmsvcl "kubectl delete service -l"
abbr --add ksysrmsvcl "kubectl --namespace=kube-system delete service -l"
abbr --add kgingl "kubectl get ingress -l"
abbr --add ksysgingl "kubectl --namespace=kube-system get ingress -l"
abbr --add kdingl "kubectl describe ingress -l"
abbr --add ksysdingl "kubectl --namespace=kube-system describe ingress -l"
abbr --add krmingl "kubectl delete ingress -l"
abbr --add ksysrmingl "kubectl --namespace=kube-system delete ingress -l"
abbr --add kgcml "kubectl get configmap -l"
abbr --add ksysgcml "kubectl --namespace=kube-system get configmap -l"
abbr --add kdcml "kubectl describe configmap -l"
abbr --add ksysdcml "kubectl --namespace=kube-system describe configmap -l"
abbr --add krmcml "kubectl delete configmap -l"
abbr --add ksysrmcml "kubectl --namespace=kube-system delete configmap -l"
abbr --add kgsecl "kubectl get secret -l"
abbr --add ksysgsecl "kubectl --namespace=kube-system get secret -l"
abbr --add kdsecl "kubectl describe secret -l"
abbr --add ksysdsecl "kubectl --namespace=kube-system describe secret -l"
abbr --add krmsecl "kubectl delete secret -l"
abbr --add ksysrmsecl "kubectl --namespace=kube-system delete secret -l"
abbr --add kgscl "kubectl get storageclass -l"
abbr --add ksysgscl "kubectl --namespace=kube-system get storageclass -l"
abbr --add kdscl "kubectl describe storageclass -l"
abbr --add ksysdscl "kubectl --namespace=kube-system describe storageclass -l"
abbr --add krmscl "kubectl delete storageclass -l"
abbr --add ksysrmscl "kubectl --namespace=kube-system delete storageclass -l"
abbr --add kgpvl "kubectl get persistentvolume -l"
abbr --add ksysgpvl "kubectl --namespace=kube-system get persistentvolume -l"
abbr --add kdpvl "kubectl describe persistentvolume -l"
abbr --add ksysdpvl "kubectl --namespace=kube-system describe persistentvolume -l"
abbr --add krmpvl "kubectl delete persistentvolume -l"
abbr --add ksysrmpvl "kubectl --namespace=kube-system delete persistentvolume -l"
abbr --add kgpvcl "kubectl get persistentvolumeclaim -l"
abbr --add ksysgpvcl "kubectl --namespace=kube-system get persistentvolumeclaim -l"
abbr --add kdpvcl "kubectl describe persistentvolumeclaim -l"
abbr --add ksysdpvcl "kubectl --namespace=kube-system describe persistentvolumeclaim -l"
abbr --add krmpvcl "kubectl delete persistentvolumeclaim -l"
abbr --add ksysrmpvcl "kubectl --namespace=kube-system delete persistentvolumeclaim -l"
abbr --add kgval "kubectl get volumeattachment -l"
abbr --add ksysgval "kubectl --namespace=kube-system get volumeattachment -l"
abbr --add kdval "kubectl describe volumeattachment -l"
abbr --add ksysdval "kubectl --namespace=kube-system describe volumeattachment -l"
abbr --add krmval "kubectl delete volumeattachment -l"
abbr --add ksysrmval "kubectl --namespace=kube-system delete volumeattachment -l"
abbr --add kgnol "kubectl get nodes -l"
abbr --add kdnol "kubectl describe nodes -l"
abbr --add krmnol "kubectl delete nodes -l"
abbr --add kgnsl "kubectl get namespaces -l"
abbr --add kdnsl "kubectl describe namespaces -l"
abbr --add krmnsl "kubectl delete namespaces -l"
abbr --add kgoyamll "kubectl get -o=yaml -l"
abbr --add ksysgoyamll "kubectl --namespace=kube-system get -o=yaml -l"
abbr --add kgpooyamll "kubectl get pods -o=yaml -l"
abbr --add ksysgpooyamll "kubectl --namespace=kube-system get pods -o=yaml -l"
abbr --add kgdepoyamll "kubectl get deployment -o=yaml -l"
abbr --add ksysgdepoyamll "kubectl --namespace=kube-system get deployment -o=yaml -l"
abbr --add kgssoyamll "kubectl get statefulset -o=yaml -l"
abbr --add ksysgssoyamll "kubectl --namespace=kube-system get statefulset -o=yaml -l"
abbr --add kgdsoyamll "kubectl get daemonset -o=yaml -l"
abbr --add ksysgdsoyamll "kubectl --namespace=kube-system get daemonset -o=yaml -l"
abbr --add kgjoboyamll "kubectl get job -o=yaml -l"
abbr --add ksysgjoboyamll "kubectl --namespace=kube-system get job -o=yaml -l"
abbr --add kgcjoboyamll "kubectl get cronjob -o=yaml -l"
abbr --add ksysgcjoboyamll "kubectl --namespace=kube-system get cronjob -o=yaml -l"
abbr --add kgsvcoyamll "kubectl get service -o=yaml -l"
abbr --add ksysgsvcoyamll "kubectl --namespace=kube-system get service -o=yaml -l"
abbr --add kgingoyamll "kubectl get ingress -o=yaml -l"
abbr --add ksysgingoyamll "kubectl --namespace=kube-system get ingress -o=yaml -l"
abbr --add kgcmoyamll "kubectl get configmap -o=yaml -l"
abbr --add ksysgcmoyamll "kubectl --namespace=kube-system get configmap -o=yaml -l"
abbr --add kgsecoyamll "kubectl get secret -o=yaml -l"
abbr --add ksysgsecoyamll "kubectl --namespace=kube-system get secret -o=yaml -l"
abbr --add kgscoyamll "kubectl get storageclass -o=yaml -l"
abbr --add ksysgscoyamll "kubectl --namespace=kube-system get storageclass -o=yaml -l"
abbr --add kgpvoyamll "kubectl get persistentvolume -o=yaml -l"
abbr --add ksysgpvoyamll "kubectl --namespace=kube-system get persistentvolume -o=yaml -l"
abbr --add kgpvcoyamll "kubectl get persistentvolumeclaim -o=yaml -l"
abbr --add ksysgpvcoyamll "kubectl --namespace=kube-system get persistentvolumeclaim -o=yaml -l"
abbr --add kgvaoyamll "kubectl get volumeattachment -o=yaml -l"
abbr --add ksysgvaoyamll "kubectl --namespace=kube-system get volumeattachment -o=yaml -l"
abbr --add kgnooyamll "kubectl get nodes -o=yaml -l"
abbr --add kgnsoyamll "kubectl get namespaces -o=yaml -l"
abbr --add kgowidel "kubectl get -o=wide -l"
abbr --add ksysgowidel "kubectl --namespace=kube-system get -o=wide -l"
abbr --add kgpoowidel "kubectl get pods -o=wide -l"
abbr --add ksysgpoowidel "kubectl --namespace=kube-system get pods -o=wide -l"
abbr --add kgdepowidel "kubectl get deployment -o=wide -l"
abbr --add ksysgdepowidel "kubectl --namespace=kube-system get deployment -o=wide -l"
abbr --add kgssowidel "kubectl get statefulset -o=wide -l"
abbr --add ksysgssowidel "kubectl --namespace=kube-system get statefulset -o=wide -l"
abbr --add kgdsowidel "kubectl get daemonset -o=wide -l"
abbr --add ksysgdsowidel "kubectl --namespace=kube-system get daemonset -o=wide -l"
abbr --add kgjobowidel "kubectl get job -o=wide -l"
abbr --add ksysgjobowidel "kubectl --namespace=kube-system get job -o=wide -l"
abbr --add kgcjobowidel "kubectl get cronjob -o=wide -l"
abbr --add ksysgcjobowidel "kubectl --namespace=kube-system get cronjob -o=wide -l"
abbr --add kgsvcowidel "kubectl get service -o=wide -l"
abbr --add ksysgsvcowidel "kubectl --namespace=kube-system get service -o=wide -l"
abbr --add kgingowidel "kubectl get ingress -o=wide -l"
abbr --add ksysgingowidel "kubectl --namespace=kube-system get ingress -o=wide -l"
abbr --add kgcmowidel "kubectl get configmap -o=wide -l"
abbr --add ksysgcmowidel "kubectl --namespace=kube-system get configmap -o=wide -l"
abbr --add kgsecowidel "kubectl get secret -o=wide -l"
abbr --add ksysgsecowidel "kubectl --namespace=kube-system get secret -o=wide -l"
abbr --add kgscowidel "kubectl get storageclass -o=wide -l"
abbr --add ksysgscowidel "kubectl --namespace=kube-system get storageclass -o=wide -l"
abbr --add kgpvowidel "kubectl get persistentvolume -o=wide -l"
abbr --add ksysgpvowidel "kubectl --namespace=kube-system get persistentvolume -o=wide -l"
abbr --add kgpvcowidel "kubectl get persistentvolumeclaim -o=wide -l"
abbr --add ksysgpvcowidel "kubectl --namespace=kube-system get persistentvolumeclaim -o=wide -l"
abbr --add kgvaowidel "kubectl get volumeattachment -o=wide -l"
abbr --add ksysgvaowidel "kubectl --namespace=kube-system get volumeattachment -o=wide -l"
abbr --add kgnoowidel "kubectl get nodes -o=wide -l"
abbr --add kgnsowidel "kubectl get namespaces -o=wide -l"
abbr --add kgojsonl "kubectl get -o=json -l"
abbr --add ksysgojsonl "kubectl --namespace=kube-system get -o=json -l"
abbr --add kgpoojsonl "kubectl get pods -o=json -l"
abbr --add ksysgpoojsonl "kubectl --namespace=kube-system get pods -o=json -l"
abbr --add kgdepojsonl "kubectl get deployment -o=json -l"
abbr --add ksysgdepojsonl "kubectl --namespace=kube-system get deployment -o=json -l"
abbr --add kgssojsonl "kubectl get statefulset -o=json -l"
abbr --add ksysgssojsonl "kubectl --namespace=kube-system get statefulset -o=json -l"
abbr --add kgdsojsonl "kubectl get daemonset -o=json -l"
abbr --add ksysgdsojsonl "kubectl --namespace=kube-system get daemonset -o=json -l"
abbr --add kgjobojsonl "kubectl get job -o=json -l"
abbr --add ksysgjobojsonl "kubectl --namespace=kube-system get job -o=json -l"
abbr --add kgcjobojsonl "kubectl get cronjob -o=json -l"
abbr --add ksysgcjobojsonl "kubectl --namespace=kube-system get cronjob -o=json -l"
abbr --add kgsvcojsonl "kubectl get service -o=json -l"
abbr --add ksysgsvcojsonl "kubectl --namespace=kube-system get service -o=json -l"
abbr --add kgingojsonl "kubectl get ingress -o=json -l"
abbr --add ksysgingojsonl "kubectl --namespace=kube-system get ingress -o=json -l"
abbr --add kgcmojsonl "kubectl get configmap -o=json -l"
abbr --add ksysgcmojsonl "kubectl --namespace=kube-system get configmap -o=json -l"
abbr --add kgsecojsonl "kubectl get secret -o=json -l"
abbr --add ksysgsecojsonl "kubectl --namespace=kube-system get secret -o=json -l"
abbr --add kgscojsonl "kubectl get storageclass -o=json -l"
abbr --add ksysgscojsonl "kubectl --namespace=kube-system get storageclass -o=json -l"
abbr --add kgpvojsonl "kubectl get persistentvolume -o=json -l"
abbr --add ksysgpvojsonl "kubectl --namespace=kube-system get persistentvolume -o=json -l"
abbr --add kgpvcojsonl "kubectl get persistentvolumeclaim -o=json -l"
abbr --add ksysgpvcojsonl "kubectl --namespace=kube-system get persistentvolumeclaim -o=json -l"
abbr --add kgvaojsonl "kubectl get volumeattachment -o=json -l"
abbr --add ksysgvaojsonl "kubectl --namespace=kube-system get volumeattachment -o=json -l"
abbr --add kgnoojsonl "kubectl get nodes -o=json -l"
abbr --add kgnsojsonl "kubectl get namespaces -o=json -l"
abbr --add kgsll "kubectl get --show-labels -l"
abbr --add ksysgsll "kubectl --namespace=kube-system get --show-labels -l"
abbr --add kgposll "kubectl get pods --show-labels -l"
abbr --add ksysgposll "kubectl --namespace=kube-system get pods --show-labels -l"
abbr --add kgdepsll "kubectl get deployment --show-labels -l"
abbr --add ksysgdepsll "kubectl --namespace=kube-system get deployment --show-labels -l"
abbr --add kgsssll "kubectl get statefulset --show-labels -l"
abbr --add ksysgsssll "kubectl --namespace=kube-system get statefulset --show-labels -l"
abbr --add kgdssll "kubectl get daemonset --show-labels -l"
abbr --add ksysgdssll "kubectl --namespace=kube-system get daemonset --show-labels -l"
abbr --add kgjobsll "kubectl get job --show-labels -l"
abbr --add ksysgjobsll "kubectl --namespace=kube-system get job --show-labels -l"
abbr --add kgcjobsll "kubectl get cronjob --show-labels -l"
abbr --add ksysgcjobsll "kubectl --namespace=kube-system get cronjob --show-labels -l"
abbr --add kgsvcsll "kubectl get service --show-labels -l"
abbr --add ksysgsvcsll "kubectl --namespace=kube-system get service --show-labels -l"
abbr --add kgingsll "kubectl get ingress --show-labels -l"
abbr --add ksysgingsll "kubectl --namespace=kube-system get ingress --show-labels -l"
abbr --add kgcmsll "kubectl get configmap --show-labels -l"
abbr --add ksysgcmsll "kubectl --namespace=kube-system get configmap --show-labels -l"
abbr --add kgsecsll "kubectl get secret --show-labels -l"
abbr --add ksysgsecsll "kubectl --namespace=kube-system get secret --show-labels -l"
abbr --add kgscsll "kubectl get storageclass --show-labels -l"
abbr --add ksysgscsll "kubectl --namespace=kube-system get storageclass --show-labels -l"
abbr --add kgpvsll "kubectl get persistentvolume --show-labels -l"
abbr --add ksysgpvsll "kubectl --namespace=kube-system get persistentvolume --show-labels -l"
abbr --add kgpvcsll "kubectl get persistentvolumeclaim --show-labels -l"
abbr --add ksysgpvcsll "kubectl --namespace=kube-system get persistentvolumeclaim --show-labels -l"
abbr --add kgvasll "kubectl get volumeattachment --show-labels -l"
abbr --add ksysgvasll "kubectl --namespace=kube-system get volumeattachment --show-labels -l"
abbr --add kgnosll "kubectl get nodes --show-labels -l"
abbr --add kgnssll "kubectl get namespaces --show-labels -l"
abbr --add kgwl "kubectl get --watch -l"
abbr --add ksysgwl "kubectl --namespace=kube-system get --watch -l"
abbr --add kgpowl "kubectl get pods --watch -l"
abbr --add ksysgpowl "kubectl --namespace=kube-system get pods --watch -l"
abbr --add kgdepwl "kubectl get deployment --watch -l"
abbr --add ksysgdepwl "kubectl --namespace=kube-system get deployment --watch -l"
abbr --add kgsswl "kubectl get statefulset --watch -l"
abbr --add ksysgsswl "kubectl --namespace=kube-system get statefulset --watch -l"
abbr --add kgdswl "kubectl get daemonset --watch -l"
abbr --add ksysgdswl "kubectl --namespace=kube-system get daemonset --watch -l"
abbr --add kgjobwl "kubectl get job --watch -l"
abbr --add ksysgjobwl "kubectl --namespace=kube-system get job --watch -l"
abbr --add kgcjobwl "kubectl get cronjob --watch -l"
abbr --add ksysgcjobwl "kubectl --namespace=kube-system get cronjob --watch -l"
abbr --add kgsvcwl "kubectl get service --watch -l"
abbr --add ksysgsvcwl "kubectl --namespace=kube-system get service --watch -l"
abbr --add kgingwl "kubectl get ingress --watch -l"
abbr --add ksysgingwl "kubectl --namespace=kube-system get ingress --watch -l"
abbr --add kgcmwl "kubectl get configmap --watch -l"
abbr --add ksysgcmwl "kubectl --namespace=kube-system get configmap --watch -l"
abbr --add kgsecwl "kubectl get secret --watch -l"
abbr --add ksysgsecwl "kubectl --namespace=kube-system get secret --watch -l"
abbr --add kgscwl "kubectl get storageclass --watch -l"
abbr --add ksysgscwl "kubectl --namespace=kube-system get storageclass --watch -l"
abbr --add kgpvwl "kubectl get persistentvolume --watch -l"
abbr --add ksysgpvwl "kubectl --namespace=kube-system get persistentvolume --watch -l"
abbr --add kgpvcwl "kubectl get persistentvolumeclaim --watch -l"
abbr --add ksysgpvcwl "kubectl --namespace=kube-system get persistentvolumeclaim --watch -l"
abbr --add kgvawl "kubectl get volumeattachment --watch -l"
abbr --add ksysgvawl "kubectl --namespace=kube-system get volumeattachment --watch -l"
abbr --add kgnowl "kubectl get nodes --watch -l"
abbr --add kgnswl "kubectl get namespaces --watch -l"
abbr --add kgowidesll "kubectl get -o=wide --show-labels -l"
abbr --add ksysgowidesll "kubectl --namespace=kube-system get -o=wide --show-labels -l"
abbr --add kgpoowidesll "kubectl get pods -o=wide --show-labels -l"
abbr --add ksysgpoowidesll "kubectl --namespace=kube-system get pods -o=wide --show-labels -l"
abbr --add kgdepowidesll "kubectl get deployment -o=wide --show-labels -l"
abbr --add ksysgdepowidesll "kubectl --namespace=kube-system get deployment -o=wide --show-labels -l"
abbr --add kgssowidesll "kubectl get statefulset -o=wide --show-labels -l"
abbr --add ksysgssowidesll "kubectl --namespace=kube-system get statefulset -o=wide --show-labels -l"
abbr --add kgdsowidesll "kubectl get daemonset -o=wide --show-labels -l"
abbr --add ksysgdsowidesll "kubectl --namespace=kube-system get daemonset -o=wide --show-labels -l"
abbr --add kgjobowidesll "kubectl get job -o=wide --show-labels -l"
abbr --add ksysgjobowidesll "kubectl --namespace=kube-system get job -o=wide --show-labels -l"
abbr --add kgcjobowidesll "kubectl get cronjob -o=wide --show-labels -l"
abbr --add ksysgcjobowidesll "kubectl --namespace=kube-system get cronjob -o=wide --show-labels -l"
abbr --add kgsvcowidesll "kubectl get service -o=wide --show-labels -l"
abbr --add ksysgsvcowidesll "kubectl --namespace=kube-system get service -o=wide --show-labels -l"
abbr --add kgingowidesll "kubectl get ingress -o=wide --show-labels -l"
abbr --add ksysgingowidesll "kubectl --namespace=kube-system get ingress -o=wide --show-labels -l"
abbr --add kgcmowidesll "kubectl get configmap -o=wide --show-labels -l"
abbr --add ksysgcmowidesll "kubectl --namespace=kube-system get configmap -o=wide --show-labels -l"
abbr --add kgsecowidesll "kubectl get secret -o=wide --show-labels -l"
abbr --add ksysgsecowidesll "kubectl --namespace=kube-system get secret -o=wide --show-labels -l"
abbr --add kgscowidesll "kubectl get storageclass -o=wide --show-labels -l"
abbr --add ksysgscowidesll "kubectl --namespace=kube-system get storageclass -o=wide --show-labels -l"
abbr --add kgpvowidesll "kubectl get persistentvolume -o=wide --show-labels -l"
abbr --add ksysgpvowidesll "kubectl --namespace=kube-system get persistentvolume -o=wide --show-labels -l"
abbr --add kgpvcowidesll "kubectl get persistentvolumeclaim -o=wide --show-labels -l"
abbr --add ksysgpvcowidesll "kubectl --namespace=kube-system get persistentvolumeclaim -o=wide --show-labels -l"
abbr --add kgvaowidesll "kubectl get volumeattachment -o=wide --show-labels -l"
abbr --add ksysgvaowidesll "kubectl --namespace=kube-system get volumeattachment -o=wide --show-labels -l"
abbr --add kgnoowidesll "kubectl get nodes -o=wide --show-labels -l"
abbr --add kgnsowidesll "kubectl get namespaces -o=wide --show-labels -l"
abbr --add kgslowidel "kubectl get --show-labels -o=wide -l"
abbr --add ksysgslowidel "kubectl --namespace=kube-system get --show-labels -o=wide -l"
abbr --add kgposlowidel "kubectl get pods --show-labels -o=wide -l"
abbr --add ksysgposlowidel "kubectl --namespace=kube-system get pods --show-labels -o=wide -l"
abbr --add kgdepslowidel "kubectl get deployment --show-labels -o=wide -l"
abbr --add ksysgdepslowidel "kubectl --namespace=kube-system get deployment --show-labels -o=wide -l"
abbr --add kgssslowidel "kubectl get statefulset --show-labels -o=wide -l"
abbr --add ksysgssslowidel "kubectl --namespace=kube-system get statefulset --show-labels -o=wide -l"
abbr --add kgdsslowidel "kubectl get daemonset --show-labels -o=wide -l"
abbr --add ksysgdsslowidel "kubectl --namespace=kube-system get daemonset --show-labels -o=wide -l"
abbr --add kgjobslowidel "kubectl get job --show-labels -o=wide -l"
abbr --add ksysgjobslowidel "kubectl --namespace=kube-system get job --show-labels -o=wide -l"
abbr --add kgcjobslowidel "kubectl get cronjob --show-labels -o=wide -l"
abbr --add ksysgcjobslowidel "kubectl --namespace=kube-system get cronjob --show-labels -o=wide -l"
abbr --add kgsvcslowidel "kubectl get service --show-labels -o=wide -l"
abbr --add ksysgsvcslowidel "kubectl --namespace=kube-system get service --show-labels -o=wide -l"
abbr --add kgingslowidel "kubectl get ingress --show-labels -o=wide -l"
abbr --add ksysgingslowidel "kubectl --namespace=kube-system get ingress --show-labels -o=wide -l"
abbr --add kgcmslowidel "kubectl get configmap --show-labels -o=wide -l"
abbr --add ksysgcmslowidel "kubectl --namespace=kube-system get configmap --show-labels -o=wide -l"
abbr --add kgsecslowidel "kubectl get secret --show-labels -o=wide -l"
abbr --add ksysgsecslowidel "kubectl --namespace=kube-system get secret --show-labels -o=wide -l"
abbr --add kgscslowidel "kubectl get storageclass --show-labels -o=wide -l"
abbr --add ksysgscslowidel "kubectl --namespace=kube-system get storageclass --show-labels -o=wide -l"
abbr --add kgpvslowidel "kubectl get persistentvolume --show-labels -o=wide -l"
abbr --add ksysgpvslowidel "kubectl --namespace=kube-system get persistentvolume --show-labels -o=wide -l"
abbr --add kgpvcslowidel "kubectl get persistentvolumeclaim --show-labels -o=wide -l"
abbr --add ksysgpvcslowidel "kubectl --namespace=kube-system get persistentvolumeclaim --show-labels -o=wide -l"
abbr --add kgvaslowidel "kubectl get volumeattachment --show-labels -o=wide -l"
abbr --add ksysgvaslowidel "kubectl --namespace=kube-system get volumeattachment --show-labels -o=wide -l"
abbr --add kgnoslowidel "kubectl get nodes --show-labels -o=wide -l"
abbr --add kgnsslowidel "kubectl get namespaces --show-labels -o=wide -l"
abbr --add kgslwl "kubectl get --show-labels --watch -l"
abbr --add ksysgslwl "kubectl --namespace=kube-system get --show-labels --watch -l"
abbr --add kgposlwl "kubectl get pods --show-labels --watch -l"
abbr --add ksysgposlwl "kubectl --namespace=kube-system get pods --show-labels --watch -l"
abbr --add kgdepslwl "kubectl get deployment --show-labels --watch -l"
abbr --add ksysgdepslwl "kubectl --namespace=kube-system get deployment --show-labels --watch -l"
abbr --add kgssslwl "kubectl get statefulset --show-labels --watch -l"
abbr --add ksysgssslwl "kubectl --namespace=kube-system get statefulset --show-labels --watch -l"
abbr --add kgdsslwl "kubectl get daemonset --show-labels --watch -l"
abbr --add ksysgdsslwl "kubectl --namespace=kube-system get daemonset --show-labels --watch -l"
abbr --add kgjobslwl "kubectl get job --show-labels --watch -l"
abbr --add ksysgjobslwl "kubectl --namespace=kube-system get job --show-labels --watch -l"
abbr --add kgcjobslwl "kubectl get cronjob --show-labels --watch -l"
abbr --add ksysgcjobslwl "kubectl --namespace=kube-system get cronjob --show-labels --watch -l"
abbr --add kgsvcslwl "kubectl get service --show-labels --watch -l"
abbr --add ksysgsvcslwl "kubectl --namespace=kube-system get service --show-labels --watch -l"
abbr --add kgingslwl "kubectl get ingress --show-labels --watch -l"
abbr --add ksysgingslwl "kubectl --namespace=kube-system get ingress --show-labels --watch -l"
abbr --add kgcmslwl "kubectl get configmap --show-labels --watch -l"
abbr --add ksysgcmslwl "kubectl --namespace=kube-system get configmap --show-labels --watch -l"
abbr --add kgsecslwl "kubectl get secret --show-labels --watch -l"
abbr --add ksysgsecslwl "kubectl --namespace=kube-system get secret --show-labels --watch -l"
abbr --add kgscslwl "kubectl get storageclass --show-labels --watch -l"
abbr --add ksysgscslwl "kubectl --namespace=kube-system get storageclass --show-labels --watch -l"
abbr --add kgpvslwl "kubectl get persistentvolume --show-labels --watch -l"
abbr --add ksysgpvslwl "kubectl --namespace=kube-system get persistentvolume --show-labels --watch -l"
abbr --add kgpvcslwl "kubectl get persistentvolumeclaim --show-labels --watch -l"
abbr --add ksysgpvcslwl "kubectl --namespace=kube-system get persistentvolumeclaim --show-labels --watch -l"
abbr --add kgvaslwl "kubectl get volumeattachment --show-labels --watch -l"
abbr --add ksysgvaslwl "kubectl --namespace=kube-system get volumeattachment --show-labels --watch -l"
abbr --add kgnoslwl "kubectl get nodes --show-labels --watch -l"
abbr --add kgnsslwl "kubectl get namespaces --show-labels --watch -l"
abbr --add kgwsll "kubectl get --watch --show-labels -l"
abbr --add ksysgwsll "kubectl --namespace=kube-system get --watch --show-labels -l"
abbr --add kgpowsll "kubectl get pods --watch --show-labels -l"
abbr --add ksysgpowsll "kubectl --namespace=kube-system get pods --watch --show-labels -l"
abbr --add kgdepwsll "kubectl get deployment --watch --show-labels -l"
abbr --add ksysgdepwsll "kubectl --namespace=kube-system get deployment --watch --show-labels -l"
abbr --add kgsswsll "kubectl get statefulset --watch --show-labels -l"
abbr --add ksysgsswsll "kubectl --namespace=kube-system get statefulset --watch --show-labels -l"
abbr --add kgdswsll "kubectl get daemonset --watch --show-labels -l"
abbr --add ksysgdswsll "kubectl --namespace=kube-system get daemonset --watch --show-labels -l"
abbr --add kgjobwsll "kubectl get job --watch --show-labels -l"
abbr --add ksysgjobwsll "kubectl --namespace=kube-system get job --watch --show-labels -l"
abbr --add kgcjobwsll "kubectl get cronjob --watch --show-labels -l"
abbr --add ksysgcjobwsll "kubectl --namespace=kube-system get cronjob --watch --show-labels -l"
abbr --add kgsvcwsll "kubectl get service --watch --show-labels -l"
abbr --add ksysgsvcwsll "kubectl --namespace=kube-system get service --watch --show-labels -l"
abbr --add kgingwsll "kubectl get ingress --watch --show-labels -l"
abbr --add ksysgingwsll "kubectl --namespace=kube-system get ingress --watch --show-labels -l"
abbr --add kgcmwsll "kubectl get configmap --watch --show-labels -l"
abbr --add ksysgcmwsll "kubectl --namespace=kube-system get configmap --watch --show-labels -l"
abbr --add kgsecwsll "kubectl get secret --watch --show-labels -l"
abbr --add ksysgsecwsll "kubectl --namespace=kube-system get secret --watch --show-labels -l"
abbr --add kgscwsll "kubectl get storageclass --watch --show-labels -l"
abbr --add ksysgscwsll "kubectl --namespace=kube-system get storageclass --watch --show-labels -l"
abbr --add kgpvwsll "kubectl get persistentvolume --watch --show-labels -l"
abbr --add ksysgpvwsll "kubectl --namespace=kube-system get persistentvolume --watch --show-labels -l"
abbr --add kgpvcwsll "kubectl get persistentvolumeclaim --watch --show-labels -l"
abbr --add ksysgpvcwsll "kubectl --namespace=kube-system get persistentvolumeclaim --watch --show-labels -l"
abbr --add kgvawsll "kubectl get volumeattachment --watch --show-labels -l"
abbr --add ksysgvawsll "kubectl --namespace=kube-system get volumeattachment --watch --show-labels -l"
abbr --add kgnowsll "kubectl get nodes --watch --show-labels -l"
abbr --add kgnswsll "kubectl get namespaces --watch --show-labels -l"
abbr --add kexn "kubectl exec -i -t --namespace"
abbr --add klon "kubectl logs -f --namespace"
abbr --add kpfn "kubectl port-forward --namespace"
abbr --add kgn "kubectl get --namespace"
abbr --add kdn "kubectl describe --namespace"
abbr --add krmn "kubectl delete --namespace"
abbr --add kgpon "kubectl get pods --namespace"
abbr --add kdpon "kubectl describe pods --namespace"
abbr --add krmpon "kubectl delete pods --namespace"
abbr --add kgdepn "kubectl get deployment --namespace"
abbr --add kddepn "kubectl describe deployment --namespace"
abbr --add krmdepn "kubectl delete deployment --namespace"
abbr --add kgssn "kubectl get statefulset --namespace"
abbr --add kdssn "kubectl describe statefulset --namespace"
abbr --add krmssn "kubectl delete statefulset --namespace"
abbr --add kgdsn "kubectl get daemonset --namespace"
abbr --add kddsn "kubectl describe daemonset --namespace"
abbr --add krmdsn "kubectl delete daemonset --namespace"
abbr --add kgjobn "kubectl get job --namespace"
abbr --add kdjobn "kubectl describe job --namespace"
abbr --add krmjobn "kubectl delete job --namespace"
abbr --add kgcjobn "kubectl get cronjob --namespace"
abbr --add kdcjobn "kubectl describe cronjob --namespace"
abbr --add krmcjobn "kubectl delete cronjob --namespace"
abbr --add kgsvcn "kubectl get service --namespace"
abbr --add kdsvcn "kubectl describe service --namespace"
abbr --add krmsvcn "kubectl delete service --namespace"
abbr --add kgingn "kubectl get ingress --namespace"
abbr --add kdingn "kubectl describe ingress --namespace"
abbr --add krmingn "kubectl delete ingress --namespace"
abbr --add kgcmn "kubectl get configmap --namespace"
abbr --add kdcmn "kubectl describe configmap --namespace"
abbr --add krmcmn "kubectl delete configmap --namespace"
abbr --add kgsecn "kubectl get secret --namespace"
abbr --add kdsecn "kubectl describe secret --namespace"
abbr --add krmsecn "kubectl delete secret --namespace"
abbr --add kgscn "kubectl get storageclass --namespace"
abbr --add kdscn "kubectl describe storageclass --namespace"
abbr --add krmscn "kubectl delete storageclass --namespace"
abbr --add kgpvn "kubectl get persistentvolume --namespace"
abbr --add kdpvn "kubectl describe persistentvolume --namespace"
abbr --add krmpvn "kubectl delete persistentvolume --namespace"
abbr --add kgpvcn "kubectl get persistentvolumeclaim --namespace"
abbr --add kdpvcn "kubectl describe persistentvolumeclaim --namespace"
abbr --add krmpvcn "kubectl delete persistentvolumeclaim --namespace"
abbr --add kgvan "kubectl get volumeattachment --namespace"
abbr --add kdvan "kubectl describe volumeattachment --namespace"
abbr --add krmvan "kubectl delete volumeattachment --namespace"
abbr --add kgoyamln "kubectl get -o=yaml --namespace"
abbr --add kgpooyamln "kubectl get pods -o=yaml --namespace"
abbr --add kgdepoyamln "kubectl get deployment -o=yaml --namespace"
abbr --add kgssoyamln "kubectl get statefulset -o=yaml --namespace"
abbr --add kgdsoyamln "kubectl get daemonset -o=yaml --namespace"
abbr --add kgjoboyamln "kubectl get job -o=yaml --namespace"
abbr --add kgcjoboyamln "kubectl get cronjob -o=yaml --namespace"
abbr --add kgsvcoyamln "kubectl get service -o=yaml --namespace"
abbr --add kgingoyamln "kubectl get ingress -o=yaml --namespace"
abbr --add kgcmoyamln "kubectl get configmap -o=yaml --namespace"
abbr --add kgsecoyamln "kubectl get secret -o=yaml --namespace"
abbr --add kgscoyamln "kubectl get storageclass -o=yaml --namespace"
abbr --add kgpvoyamln "kubectl get persistentvolume -o=yaml --namespace"
abbr --add kgpvcoyamln "kubectl get persistentvolumeclaim -o=yaml --namespace"
abbr --add kgvaoyamln "kubectl get volumeattachment -o=yaml --namespace"
abbr --add kgowiden "kubectl get -o=wide --namespace"
abbr --add kgpoowiden "kubectl get pods -o=wide --namespace"
abbr --add kgdepowiden "kubectl get deployment -o=wide --namespace"
abbr --add kgssowiden "kubectl get statefulset -o=wide --namespace"
abbr --add kgdsowiden "kubectl get daemonset -o=wide --namespace"
abbr --add kgjobowiden "kubectl get job -o=wide --namespace"
abbr --add kgcjobowiden "kubectl get cronjob -o=wide --namespace"
abbr --add kgsvcowiden "kubectl get service -o=wide --namespace"
abbr --add kgingowiden "kubectl get ingress -o=wide --namespace"
abbr --add kgcmowiden "kubectl get configmap -o=wide --namespace"
abbr --add kgsecowiden "kubectl get secret -o=wide --namespace"
abbr --add kgscowiden "kubectl get storageclass -o=wide --namespace"
abbr --add kgpvowiden "kubectl get persistentvolume -o=wide --namespace"
abbr --add kgpvcowiden "kubectl get persistentvolumeclaim -o=wide --namespace"
abbr --add kgvaowiden "kubectl get volumeattachment -o=wide --namespace"
abbr --add kgojsonn "kubectl get -o=json --namespace"
abbr --add kgpoojsonn "kubectl get pods -o=json --namespace"
abbr --add kgdepojsonn "kubectl get deployment -o=json --namespace"
abbr --add kgssojsonn "kubectl get statefulset -o=json --namespace"
abbr --add kgdsojsonn "kubectl get daemonset -o=json --namespace"
abbr --add kgjobojsonn "kubectl get job -o=json --namespace"
abbr --add kgcjobojsonn "kubectl get cronjob -o=json --namespace"
abbr --add kgsvcojsonn "kubectl get service -o=json --namespace"
abbr --add kgingojsonn "kubectl get ingress -o=json --namespace"
abbr --add kgcmojsonn "kubectl get configmap -o=json --namespace"
abbr --add kgsecojsonn "kubectl get secret -o=json --namespace"
abbr --add kgscojsonn "kubectl get storageclass -o=json --namespace"
abbr --add kgpvojsonn "kubectl get persistentvolume -o=json --namespace"
abbr --add kgpvcojsonn "kubectl get persistentvolumeclaim -o=json --namespace"
abbr --add kgvaojsonn "kubectl get volumeattachment -o=json --namespace"
abbr --add kgsln "kubectl get --show-labels --namespace"
abbr --add kgposln "kubectl get pods --show-labels --namespace"
abbr --add kgdepsln "kubectl get deployment --show-labels --namespace"
abbr --add kgsssln "kubectl get statefulset --show-labels --namespace"
abbr --add kgdssln "kubectl get daemonset --show-labels --namespace"
abbr --add kgjobsln "kubectl get job --show-labels --namespace"
abbr --add kgcjobsln "kubectl get cronjob --show-labels --namespace"
abbr --add kgsvcsln "kubectl get service --show-labels --namespace"
abbr --add kgingsln "kubectl get ingress --show-labels --namespace"
abbr --add kgcmsln "kubectl get configmap --show-labels --namespace"
abbr --add kgsecsln "kubectl get secret --show-labels --namespace"
abbr --add kgscsln "kubectl get storageclass --show-labels --namespace"
abbr --add kgpvsln "kubectl get persistentvolume --show-labels --namespace"
abbr --add kgpvcsln "kubectl get persistentvolumeclaim --show-labels --namespace"
abbr --add kgvasln "kubectl get volumeattachment --show-labels --namespace"
abbr --add kgwn "kubectl get --watch --namespace"
abbr --add kgpown "kubectl get pods --watch --namespace"
abbr --add kgdepwn "kubectl get deployment --watch --namespace"
abbr --add kgsswn "kubectl get statefulset --watch --namespace"
abbr --add kgdswn "kubectl get daemonset --watch --namespace"
abbr --add kgjobwn "kubectl get job --watch --namespace"
abbr --add kgcjobwn "kubectl get cronjob --watch --namespace"
abbr --add kgsvcwn "kubectl get service --watch --namespace"
abbr --add kgingwn "kubectl get ingress --watch --namespace"
abbr --add kgcmwn "kubectl get configmap --watch --namespace"
abbr --add kgsecwn "kubectl get secret --watch --namespace"
abbr --add kgscwn "kubectl get storageclass --watch --namespace"
abbr --add kgpvwn "kubectl get persistentvolume --watch --namespace"
abbr --add kgpvcwn "kubectl get persistentvolumeclaim --watch --namespace"
abbr --add kgvawn "kubectl get volumeattachment --watch --namespace"
abbr --add kgowidesln "kubectl get -o=wide --show-labels --namespace"
abbr --add kgpoowidesln "kubectl get pods -o=wide --show-labels --namespace"
abbr --add kgdepowidesln "kubectl get deployment -o=wide --show-labels --namespace"
abbr --add kgssowidesln "kubectl get statefulset -o=wide --show-labels --namespace"
abbr --add kgdsowidesln "kubectl get daemonset -o=wide --show-labels --namespace"
abbr --add kgjobowidesln "kubectl get job -o=wide --show-labels --namespace"
abbr --add kgcjobowidesln "kubectl get cronjob -o=wide --show-labels --namespace"
abbr --add kgsvcowidesln "kubectl get service -o=wide --show-labels --namespace"
abbr --add kgingowidesln "kubectl get ingress -o=wide --show-labels --namespace"
abbr --add kgcmowidesln "kubectl get configmap -o=wide --show-labels --namespace"
abbr --add kgsecowidesln "kubectl get secret -o=wide --show-labels --namespace"
abbr --add kgscowidesln "kubectl get storageclass -o=wide --show-labels --namespace"
abbr --add kgpvowidesln "kubectl get persistentvolume -o=wide --show-labels --namespace"
abbr --add kgpvcowidesln "kubectl get persistentvolumeclaim -o=wide --show-labels --namespace"
abbr --add kgvaowidesln "kubectl get volumeattachment -o=wide --show-labels --namespace"
abbr --add kgslowiden "kubectl get --show-labels -o=wide --namespace"
abbr --add kgposlowiden "kubectl get pods --show-labels -o=wide --namespace"
abbr --add kgdepslowiden "kubectl get deployment --show-labels -o=wide --namespace"
abbr --add kgssslowiden "kubectl get statefulset --show-labels -o=wide --namespace"
abbr --add kgdsslowiden "kubectl get daemonset --show-labels -o=wide --namespace"
abbr --add kgjobslowiden "kubectl get job --show-labels -o=wide --namespace"
abbr --add kgcjobslowiden "kubectl get cronjob --show-labels -o=wide --namespace"
abbr --add kgsvcslowiden "kubectl get service --show-labels -o=wide --namespace"
abbr --add kgingslowiden "kubectl get ingress --show-labels -o=wide --namespace"
abbr --add kgcmslowiden "kubectl get configmap --show-labels -o=wide --namespace"
abbr --add kgsecslowiden "kubectl get secret --show-labels -o=wide --namespace"
abbr --add kgscslowiden "kubectl get storageclass --show-labels -o=wide --namespace"
abbr --add kgpvslowiden "kubectl get persistentvolume --show-labels -o=wide --namespace"
abbr --add kgpvcslowiden "kubectl get persistentvolumeclaim --show-labels -o=wide --namespace"
abbr --add kgvaslowiden "kubectl get volumeattachment --show-labels -o=wide --namespace"
abbr --add kgslwn "kubectl get --show-labels --watch --namespace"
abbr --add kgposlwn "kubectl get pods --show-labels --watch --namespace"
abbr --add kgdepslwn "kubectl get deployment --show-labels --watch --namespace"
abbr --add kgssslwn "kubectl get statefulset --show-labels --watch --namespace"
abbr --add kgdsslwn "kubectl get daemonset --show-labels --watch --namespace"
abbr --add kgjobslwn "kubectl get job --show-labels --watch --namespace"
abbr --add kgcjobslwn "kubectl get cronjob --show-labels --watch --namespace"
abbr --add kgsvcslwn "kubectl get service --show-labels --watch --namespace"
abbr --add kgingslwn "kubectl get ingress --show-labels --watch --namespace"
abbr --add kgcmslwn "kubectl get configmap --show-labels --watch --namespace"
abbr --add kgsecslwn "kubectl get secret --show-labels --watch --namespace"
abbr --add kgscslwn "kubectl get storageclass --show-labels --watch --namespace"
abbr --add kgpvslwn "kubectl get persistentvolume --show-labels --watch --namespace"
abbr --add kgpvcslwn "kubectl get persistentvolumeclaim --show-labels --watch --namespace"
abbr --add kgvaslwn "kubectl get volumeattachment --show-labels --watch --namespace"
abbr --add kgwsln "kubectl get --watch --show-labels --namespace"
abbr --add kgpowsln "kubectl get pods --watch --show-labels --namespace"
abbr --add kgdepwsln "kubectl get deployment --watch --show-labels --namespace"
abbr --add kgsswsln "kubectl get statefulset --watch --show-labels --namespace"
abbr --add kgdswsln "kubectl get daemonset --watch --show-labels --namespace"
abbr --add kgjobwsln "kubectl get job --watch --show-labels --namespace"
abbr --add kgcjobwsln "kubectl get cronjob --watch --show-labels --namespace"
abbr --add kgsvcwsln "kubectl get service --watch --show-labels --namespace"
abbr --add kgingwsln "kubectl get ingress --watch --show-labels --namespace"
abbr --add kgcmwsln "kubectl get configmap --watch --show-labels --namespace"
abbr --add kgsecwsln "kubectl get secret --watch --show-labels --namespace"
abbr --add kgscwsln "kubectl get storageclass --watch --show-labels --namespace"
abbr --add kgpvwsln "kubectl get persistentvolume --watch --show-labels --namespace"
abbr --add kgpvcwsln "kubectl get persistentvolumeclaim --watch --show-labels --namespace"
abbr --add kgvawsln "kubectl get volumeattachment --watch --show-labels --namespace"
